### ISSUE TITLE
Suppress display of Start Date and End Date if the values are empty

### ISSUE THREAD

**Issue by bmuramatsu** [digitalcredentials/learner-credential-wallet#102]
If the issuer does not provide a Start Date and End Date supress the display on the Credential Card.

It might currently be showing the date the credential is added if no dates are present.

**Comment by mlisle** [comment]
Now that you mention it... What fields are supposed to be used for start/end dates? I think @stuartf and I were assuming that one of those two would be issuanceDate, but that doesn't appear to be the case.

**Comment by bmuramatsu** [comment]
I think of these as when the program for which the credential applies started and ended. So the start and end date of the term, or start and end date of the degree. @dmitrizagidulin can clarify further.
