### ISSUE TITLE
BUG: Sharing Credentials as VP does not work for certain @context's

### ISSUE THREAD

**Issue by csehlke** [digitalcredentials/learner-credential-wallet#183]
**Using:**
- Android 11
- LCW v1.4.1

**Issue:**
When trying to share a credentials via the "Share" page that contains one of those context uris ("http://home.in.tum.de/~sehlke/elmoLearner.json", "https://w3id.org/vc-revocation-list-2020/v1") the app simple does nothing.

**Expectation:**
When pressing the "Send" button in the "Share Preview" Page the app should create a presentation with the selected credentials and open Android's share menu as it does for other credentials (that do not contain any of the listed context uris).
Currently only very specific credentials can be shared and be presented to a verifying party and for all others it simple does not work (yet).

**Steps to reproduce:**
- load the credential into the wallet via a QR-Code (dccrequest://request?&auth_type=bearer&issuer=example.org&vc_request_url=http://localhost:3000/credential&challenge=123)
- open the "Share" page in the app
- select the just added credential
- press "Share Selected Credential"
- press "Send"

For following credential
```
{
    "@context": [
        "https://www.w3.org/2018/credentials/v1",
        "https://w3id.org/security/suites/ed25519-2020/v1"
    ],
    "id": "http://localhost:8082/credentials/29",
    "type": ["VerifiableCredential"],
    "issuer": "did:key:z6MkqVmUBC49F98kvo5bC2Me6PpT3C1YjMGNRXi1Ci312zms",
    "issuanceDate": "2022-06-15T15:05:01Z",
    "credentialSubject": {
        "id": "did:ethr:0x1844d35477a3eea17dece6d1ac6a9f91d20a5140"
    }
}
```
- Android's share menu appears with a presentation containing the selected credential ✔️ 

And for the following credential
```
{
    "@context": [
        "https://www.w3.org/2018/credentials/v1",
        "https://w3id.org/vc-revocation-list-2020/v1",
        "https://w3id.org/security/suites/ed25519-2020/v1"
    ],
    "id": "http://localhost:8082/credentials/29",
    "type": ["VerifiableCredential"],
    "issuer": "did:key:z6MkqVmUBC49F98kvo5bC2Me6PpT3C1YjMGNRXi1Ci312zms",
    "issuanceDate": "2022-06-15T15:05:01Z",
    "credentialSubject": {
        "id": "did:ethr:0x1844d35477a3eea17dece6d1ac6a9f91d20a5140"
    }
}
```
- simply nothing happens ❌

**Comment by kayaelle** [comment]
@dmitrizagidulin - is this issue because the LCW is only working with open badges 3.0 currently?

**Comment by kayaelle** [comment]
Assigning for testing by our team.

**Comment by IsaacAirmet1** [comment]
Tested and no issues found.

**Comment by kayaelle** [comment]
Thanks @IsaacAirmet1
