### ISSUE TITLE
Feature Request: Verifiable Presentation creation with server-provided challenge

### ISSUE THREAD

**Issue by jfelixh** [digitalcredentials/learner-credential-wallet#185]
### Short Description

Right now, LCW is able to generate a Verifiable Presentation (VP) using a random UUID as challenge. To confirm that a given VP was generated intentionally for a given third party, it is necessary to have that challenge supplied by that third party.

### Target Process Outline

This could be very similar to the current process for loading credentials into the wallet, hopefully minimizing required changes:

1. Our web app generates a qr code with the following information
    1. Random server-generated challenge
    2. API endpoint URL to send the VP to

```
dccrequest://present?              // DCC: mobile app deep link
&vc_present_url=<vc_present_url>   // DCC: verifiable credential present url
&challenge=<challenge>             // DCC: challenge for signing
```

2. After scanning the code with the smartphone camera, the LCW can generate the VP using the provided challenge.
    1. The order of sub-actions here is not clear. Either selecting credentials for the VP, or scanning the code could happen first.
4. The finished VP is sent from the LCW to the API endpoint obtained previously from the qr code.
5. Our server can validate that the VP is valid and uses the correct challenge.

**Comment by dmitrizagidulin** [comment]
This feature has been implemented, closing.
