### ISSUE TITLE
'No DID' error when initializing wallet

### ISSUE THREAD

**Issue by jchartrand** [digitalcredentials/learner-credential-wallet#193]
@dmitrizagidulin As requested, posting the error we talked about on the DCC call earlier this morning.

Error that appears on the emulator screen: "No DID generated. Something went wrong in wallet initialization."

Screen shot:

![Simulator Screen Shot - iPhone 13 - 2022-08-18 at 11 24 09](https://user-images.githubusercontent.com/547165/185433127-432889d0-1a81-4ba3-9f86-0034105adbd9.png)

Which might be caused by this underlying error in the didState/addDidRecord action (screen shot):

<img width="1236" alt="image" src="https://user-images.githubusercontent.com/547165/185434211-29bae6a2-d239-4fab-8a9c-0bec2f0edbc2.png">

This is on a MacBook Pro (M1 Pro) running Monterey 12.5.  Running the emulator from the cloned GitHub project with the package.json 'ios' script (react-native run-ios).  Emulating iPhone 13, iOS 15.5.

**Comment by dmitrizagidulin** [comment]
@jchartrand - I think this has been fixed in main. If you don't mind, re-test and close.

**Comment by dmitrizagidulin** [comment]
Fixed, closing. (Please feel free to reopen if you encounter this issue again).
