### ISSUE TITLE
Add to LinkedIn Profile removed Credential URL and retains Credential ID

### ISSUE THREAD

**Issue by bmuramatsu** [digitalcredentials/learner-credential-wallet#201]
This may have been wrong in the PR, but it's definitely wrong in the build.

Add to LinkedIn Profile should have the VerifierPlus public share URL and no Credential ID.

**Comment by kayaelle** [comment]
Dmitri will test after publishing LinkedIn date fix.

**Comment by kayaelle** [comment]
@dmitrizagidulin - please check to see if this was included in recent build.

**Comment by dmitrizagidulin** [comment]
Ah ok, I think I may have misunderstood the issue originally. The Credential ID /is/ still being included. I'll remove it and republish.

**Comment by kayaelle** [comment]
@dmitrizagidulin - can this be closed?

**Comment by kayaelle** [comment]
Looks good @dmitrizagidulin

**Comment by bmuramatsu** [comment]
@dmitrizagidulin For LCW v2.0.11-Build 66, both iOS and Android, I'm still seeing our urn:uuid... in the Credential  ID field when Adding to LinkedIn.

**Comment by kayaelle** [comment]
I've confirmed that credential id is empty when sharing a credential to LinkedIn in both iOS and Android.
