### ISSUE TITLE
Learner Credential Issuer - token/DID exchange handling

### ISSUE THREAD

**Issue by jchartrand** [digitalcredentials/learner-credential-wallet#206]
Build a module (call it Learner Credential Issuer - LCI for ease of reference ) that simplifies issuing to the LCW, most specifically by managing a token/DID exchange between wallet and server, thereby removing the need to directly tie an issuer's OAuth system into the wallet.

The LCI could also optionally handle all the other bits like constructing the VC, signing, logging, revocation allocation, thereby making it quite a bit simpler for a new issuer to get up and running.

The LCI could be set up as a simple http server (e.g., Node Express) with two endpoints:

/issueCredential  (called by issuer)
/collectCredential  (called by wallet, passing holder DID)

The fundamental flow (see the diagram below) is that a request for a credential is made from a web page behind the issuer's standard authentication system (e.g., Azure), i.e, after the student has logged into the campus system.  When the credential is requested, the issuer retrieves the student's data from the database and then redirects the initial http request to the 'issueCredential' endpoint of the LCI , passing along the data needed to populate the credential.  The endpoint receives the data and stores it as the 'value' in a simple in-memory key-value store, with the key a new UUID.  The endpoint then redirects to a deeplink that opens the LCW, passing along the UUID.  The wallet opens, prompts the user to accept the credential and choose a profile/DID, then submits that DID (as a DIDAuthResponse) back to the /collectCredential endpoint where the LCI receives the DID, adds it to the VC as the subject, signs the VC and returns it.

Note: could split out the piece that handles the DID exchange with the wallet, to make it easier for projects to just use that piece - basically to provide a 'standard' non-OAuth way to collect the holder's DID.

Note that a lot of this is probably already part of sign-and-verify and so this could simply be adding two endpoints to sign-and-verify.

<img width="628" alt="image" src="https://user-images.githubusercontent.com/547165/187945620-888aa483-aa9d-4147-aa90-d408e894962b.png">

**Comment by kayaelle** [comment]
Thanks for submitting this @jchartrand!

(I asked James to add to this repository because it was related to the wallet but this suggestion could easily be its own repo or in the sign and verify.

Ideas to make the issuing flow easier are worth exploring. Would these remove did auth from the issuing flow which ensures that the issuer is able to verify that the subject does have control of that DID.  What are the drawbacks to that?

**Comment by jchartrand** [comment]
@kayaelle 

The holder/subject would still use DIDAuth to submit their DID.  In other words, when the LCW submits the subject's DID, it would demonstrate control by signing with the private key.

This part of the flow wouldn't change from what the LCW currently does.  In fact, I suspect very few - if any - changes would be needed to the LCW.  I think the LCW already accommodates this flow.

The point of this is just to simplify the token/DID exchange on the issuer's side.

**Comment by kayaelle** [comment]
@jchartrand  So the LCI would be the software that does the DID resolution? Would you see the LCI being used predominantly as a service endpoint or one an issuing org would install as a helpful library?

**Comment by jchartrand** [comment]
@kayaelle I suppose the LCI would have to resolve the submitted holder's DID, so as to know that a valid private key was used to sign the DIDAuth.  But, that resolution would be done by some other library/service (e.g., https://github.com/decentralized-identity/universal-resolver).

I could see the LCI being used either way - as an npm library or as a service endpoint.  Much like sign-and-verify-core and sign-and-verify.  I could also imagine the service endpoint being run either locally by an issuer, or as a DCC hosted endpoint.

**Comment by kayaelle** [comment]
Thanks @jchartrand Looking forward to discussing it more with @dmitrizagidulin

**Comment by alexfigtree** [comment]
@jchartrand What would you like to do with this issue?

**Comment by jchartrand** [comment]
@alexfigtree This has been effectively implemented in the exchange coordinator, so can be closed

**Comment by kayaelle** [comment]
Closing per @jchartrand
