### ISSUE TITLE
Enable/fix scanning of QR codes containing URLs to credentials

### ISSUE THREAD

**Issue by dmitrizagidulin** [digitalcredentials/learner-credential-wallet#249]
LCW should support scanning of a QR code (on the Add Credential screen) that contains a URL to a cloud-hosted Verifiable Presentation. (I vaguely remember us implementing this earlier, but it doesn't seem to be working):

So, for example, when in LCW I scan the following QR code:
![qr](https://user-images.githubusercontent.com/947005/199535985-5a1e2eec-8801-4e18-aa5a-a9976514d564.svg)

it decodes to the following Gist:
https://gist.githubusercontent.com/dmitrizagidulin/c51ba271196d2b55119063db90e86437/raw/e52d34119c961e5d680f8a86ef82541843820182/sample-vc.json

The wallet should fetch the contents of the URL, and if it contains JSON, attempt to parse it, and add it via the same channel as if it was scanned via embedded VPQR-encode QR code.

**Comment by dmitrizagidulin** [comment]
(Apologies for the giant image)

**Comment by sethduffin** [comment]
@dmitrizagidulin I believe we can close this one as well

**Comment by bmuramatsu** [comment]
Works iOS and Android build 52
