### ISSUE TITLE
Add Challenge Field Support for Sharing Credentials

### ISSUE THREAD

**Issue by bmuramatsu** [digitalcredentials/learner-credential-wallet#261]
Current workflow: LCW generates a random challenge field that is a protection against replay attacks from the requester of a shared credential.

New workflow: Recipient of a presentation (to whom I want share a credential with) provides a challenge, LCW puts the challenge in the VP and returns it to the recipient/requester at the specified API endpoint.

Workflow:
1. Requester asks me to provide diploma (requests a VP)
2. Requester provides a QR code to communicate 1) the challenge and 2) the API endpoint describing where to send the credentials, to the wallet (A)
3. Wallet extracts challenge and API endpoint
4. User selects / confirms which credentials to share (MVP full list of credentials from wallet from all profiles) (B and C)
5. Wallet produces a VP including the challenge
6. Wallet POSTs to provided API endpoint (D)

MVP implements via scanning the request via a QR code.

MVP implements workflow without user feedback.

A-D above are user feedback opportunities, potential text suggested below:
A. Who is requesting and which credential(s). <name> is requesting the following crendential(s): <list of credentials>, do you to share them? Share / Don't Share (Cancel).
B. You are going to share <name of credentials> to <name>. Proceed / Cancel.
C. Please confirm sharing <name of credentials> to <name>. Proceed / Cancel
D. Result of operation: Your credential has been shared successfully. Your credential could not be shared.

**Comment by dmitrizagidulin** [comment]
This has been implemented as part of issue #262, closing.
