### ISSUE TITLE
Add CHAPI support for Share Credential Request workflow - Get Requests

### ISSUE THREAD

**Issue by bmuramatsu** [digitalcredentials/learner-credential-wallet#263]
Add CHAPI support for Share Credential Request workflow.

Note: This issue is for _presenting_ a credential from LCW (hence the Share Credential Request) part. 
For support for issuing a VC _into_ LCW, see issue https://github.com/digitalcredentials/learner-credential-wallet/issues/504

**Comment by bmuramatsu** [comment]
Works in Android, Build 52

**Comment by kayaelle** [comment]
@dmitrizagidulin - please add instructions for Atomic Jolt team

**Comment by alexfigtree** [comment]
Seeing this in iOS:
![screenshot_2024-01-23_at_1 47 07___pm](https://github.com/digitalcredentials/learner-credential-wallet/assets/3487193/fce9b548-770c-4414-8a00-3579e5f00162)

**Comment by alexfigtree** [comment]
Issue blocked on https://github.com/digitalcredentials/learner-credential-wallet/issues/547.

**Comment by dmitrizagidulin** [comment]
Ok, #547 has been fixed, but now blocked on issue https://github.com/digitalcredentials/learner-credential-wallet/issues/598

**Comment by alexfigtree** [comment]
Both https://github.com/digitalcredentials/learner-credential-wallet/issues/547 and https://github.com/digitalcredentials/learner-credential-wallet/issues/598 have been closed, can now close this issue.
