### ISSUE TITLE
Create Template Repo for JSON-LD Context NPM Package

### ISSUE THREAD

**Issue by kayaelle** [digitalcredentials/learner-credential-wallet#265]
Please duplicate this repo: https://github.com/digitalcredentials/open-badges-context to create a github repo template that can be used for future JSON-LD npm context modules that are used by the LCW document loader.

Name suggestion: JSON-LD Context NPM Package Template
The README can also model the readme in the OB context module with edits referencing it as the template repo.

@dmitrizagidulin - how's this name?

See: [https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository](https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository)

**Comment by dmitrizagidulin** [comment]
Template exists, closing https://github.com/digitalcredentials/jsonld-context-template
