### ISSUE TITLE
Add screenshots to Readme

### ISSUE THREAD

**Issue by dmitrizagidulin** [digitalcredentials/learner-credential-wallet#267]
Let's add a handful of LCW screenshots to the Readme -- it's super helpful for new developers or prospects.

**Comment by Shruti3004** [comment]
Hey @dmitrizagidulin I want to work on this issue

**Comment by dmitrizagidulin** [comment]
@Shruti3004 that would be wonderful!

**Comment by bmuramatsu** [comment]
Shruti,

Thanks for your contributions. I'm the product manager for the Learner
Credential Wallet.

A couple suggestions before you get started:

   - Make a list of screenshots you think would be helpful
   - Presumably use dark mode

A couple requirements, for while this is a cross platform app, our primary
development focuses on iOS:

   - Take the screenshots on an iPhone or via Simulator
   - Set the device time to 9:41 so all screenshots--current and
   future--appear to have been taken at the same time
   - Follow the Apple App Store guidelines for screenshot sizes,
   https://help.apple.com/app-store-connect/#/devd274dd925
   - (Note if I were doing this I'd do it from my iPhone 13 Pro so I'd end
   up with one of the 5.8" dimension images, I'd connect my iPhone to
   Quicktime to set the clock to 9:41, take the screenshot on my iPhone and
   upload it with alt text and a descriptive caption.)
   - (I ask for the above so we have consistency between new and old
   screenshots if we end up mixing and matching across different releases)

Also, you may want to consider whether it would be best to match the
existing style and tone of the documentation when suggesting changes to the
documentation.

Also note that if you build the app from main you'll have all the current
features and that's more than the app store versions. We'll release new app
store versions hopefully by the end of the year.

Brandon

**Comment by kayaelle** [comment]
@fields37 - would you like to give this a shot?

**Comment by bmuramatsu** [comment]
[4 screenshots](https://github.com/digitalcredentials/learner-credential-wallet/tree/main/docs) that can be posted to the code library.

**Comment by fields37** [comment]
Thanks Brandon, am I missing something or are these just going into the [readme file](https://github.com/digitalcredentials/learner-credential-wallet/blob/main/README.md)?

**Comment by bmuramatsu** [comment]
Correct, please add to the Readme.

I think it's odd to add the screenshots here as this is the source code and
we run a separate website for the app and having to keep these up to date
also is additional maintenance burden... but nonetheless here are 3
screenshots. I'd place them above the Goals line, and make them relatively
small images on a single line so as not to take up too much space. Thanks.

**Comment by alexfigtree** [comment]
Screenshots added, closing ticket
