### ISSUE TITLE
Add "What does this mean" to Verification Screen

### ISSUE THREAD

**Issue by bmuramatsu** [digitalcredentials/learner-credential-wallet#277]
Provide additional description of what the various verification checks mean on the Verification screen intended for end users (learners and employers) to understand what verification means.

Might be best to do this on LCW.app and link to it from LCW, the LCW FAQ and the VerifierPlus FAQ.

**Comment by bmuramatsu** [comment]
Link to https://lcw.app/faq.html#verificationstatus

**Comment by kayaelle** [comment]
Needs design follow-up for link placement
