### ISSUE TITLE
Loading config URL from .env not working for iOS build

### ISSUE THREAD

**Issue by dmitrizagidulin** [digitalcredentials/learner-credential-wallet#278]
Loading `VERIFIER_PLUS_URL` from `@env` (like is done here: https://github.com/digitalcredentials/learner-credential-wallet/blob/main/app/lib/verifierPlus.ts#L1 ) 
is not working for me.

To replicate:
- copy `.env.example` to `.env`
- in .env, set `VERIFIER_PLUS_URL` to its prod value
- build an iOS build and test out creating a public link for a VC. if you put in a console.log in `verifierPlus.ts`, you'll see `VERIFIER_PLUS_URL` value is undefined.

**Comment by sethduffin** [comment]
Right now we have it set to read the env file: `.env.local` but we can update this in `babel.config.js`

**Comment by dmitrizagidulin** [comment]
@sethduffin Understood, thanks. Closing.
