### ISSUE TITLE
Android, Lightmode, Custom setup dialog box with cancel visible on screen after entering password

### ISSUE THREAD

**Issue by bmuramatsu** [digitalcredentials/learner-credential-wallet#299]

**Comment by sethduffin** [comment]
@bmuramatsu I'm not sure I follow, could you provide more information on this issue?

**Comment by bmuramatsu** [comment]
![IMG_7259](https://user-images.githubusercontent.com/752326/208555130-0a65abce-0eed-4486-b5a6-3f5fe381524a.png)

**Comment by sethduffin** [comment]
Thanks! This will be fixed in #321
