### ISSUE TITLE
Create new profile OS adds a space after autocomplete to end of profile name

### ISSUE THREAD

**Issue by bmuramatsu** [digitalcredentials/learner-credential-wallet#324]
Is there any way of preventing the OS (iOS in my test case) from adding a space at the end of a to be create profile name?

Or deleting the space on save?

**Comment by dmitrizagidulin** [comment]
+1 to deleting a trailing space on save

**Comment by jmcioffi4** [comment]
Attempted to create a new profile (on iOS) in `Manage Profiles` and typed in `Test` as the name. Went in to re-name it, do not see an extra space. Also do not see it inside of the source:
```
{
  "_id": "64e6484a400065baa2e3adee",
  "createdAt": "2023-08-23T17:56:26.162Z",
  "updatedAt": "2023-08-23T17:56:26.162Z",
  "profileName": "Test", // NO TRAILING SPACE HERE
  "didRecordId": "64e6484a400065baa2e3aded",
  "rawCredentialRecords": []
}
```

if you're talking about auto-complete, that is most likely an OS piece of code we cannot change, as that I have seen occur EVERYWHERE that auto-complete is used (in iOS at least). So I don't believe we have the power to change that.

@dmitrizagidulin @bmuramatsu could you please further elaborate if you find this is still an issue?

**Comment by bmuramatsu** [comment]
I am not seeing the extra space that I must've when I created this issue. I am not seeing an extra space when I type in a new name or paste in text. 

I think it's fine to close this issue.
