### ISSUE TITLE
Bold Learner Credential Wallet text on about screen

### ISSUE THREAD

**Issue by bmuramatsu** [digitalcredentials/learner-credential-wallet#325]
Just to make it look better.

**Comment by kayaelle** [comment]
Screenshot for reference.

<img width="414" alt="signal-2023-05-02-162609" src="https://user-images.githubusercontent.com/206059/235778233-9f4f26ad-7354-44f6-8918-387536ae60be.png">

**Comment by bmuramatsu** [comment]
"Learner Credential Wallet" text is now bold on the About screen, but so is all the rest of the text.

All text on the screen is bold in iOS and Android LCW v2.0.11-Builds 8-11.

Revert display of all of the rest of the text to non-bold as in v2.0.7-Build 62 and as seen in the screenshot from iOS below.

**Non-bold rest of text on About screen**
<img src="https://github.com/digitalcredentials/learner-credential-wallet/assets/752326/d05dd76c-ff66-4377-90ec-e6cb742fa866" width=30%>

**Comment by kayaelle** [comment]
Moving this one to LCW backlog for rescheduling.
