### ISSUE TITLE
Non-revoked credential with status QR code shows as revoked

### ISSUE THREAD

**Issue by bmuramatsu** [digitalcredentials/learner-credential-wallet#335]
From Issue 10, Non-revoked credential with status QR code

![185563761-01a8553f-4e36-43e6-9e6a-bbf4246d0155](https://user-images.githubusercontent.com/752326/208930803-1d2e45ea-01ce-4053-9603-ce53ec2ba538.gif)

Shows as revoked.
JSON:

```json
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://w3id.org/security/suites/ed25519-2020/v1",
    "https://w3id.org/dcc/v1",
    "https://w3id.org/vc/status-list/2021/v1"
  ],
  "type": [
    "VerifiableCredential",
    "Assertion"
  ],
  "credentialStatus": {
    "type": "StatusList2021Entry",
    "id": "https://digitalcredentials.github.io/credential-status-playground/JWZM3H8WKU#2",
    "statusListCredential": "https://digitalcredentials.github.io/credential-status-playground/JWZM3H8WKU",
    "statusListIndex": 2,
    "statusPurpose": "revocation"
  },
  "credentialSubject": {
    "hasCredential": {
      "type": [
        "EducationalOccupationalCredential"
      ],
      "description": "The holder of this credential is qualified to lead new student orientations.",
      "name": "GT Guide"
    },
    "id": "did:key:z6MkhVTX9BF3NGYX6cc7jWpbNnR7cAjH8LUffabZP8Qu4ysC",
    "name": "Kayode Ezike"
  },
  "expirationDate": "2025-08-16T12:00:00.000+00:00",
  "issuanceDate": "2020-08-16T12:00:00.000+00:00",
  "issuer": {
    "id": "did:key:z6MkhVTX9BF3NGYX6cc7jWpbNnR7cAjH8LUffabZP8Qu4ysC",
    "image": "https://user-images.githubusercontent.com/947005/133544904-29d6139d-2e7b-4fe2-b6e9-7d1022bb6a45.png",
    "name": "Example University",
    "url": "https://cs.example.edu/"
  },
  "proof": {
    "type": "Ed25519Signature2020",
    "created": "2022-08-19T06:55:17Z",
    "proofPurpose": "assertionMethod",
    "proofValue": "z4EiTbmC79r4dRaqLQZr2yxQASoMKneHVNHVaWh1xcDoPG2eTwYjKoYaku1Canb7a6Xp5fSogKJyEhkZCaqQ6Y5nw",
    "verificationMethod": "did:key:z6MkhVTX9BF3NGYX6cc7jWpbNnR7cAjH8LUffabZP8Qu4ysC#z6MkhVTX9BF3NGYX6cc7jWpbNnR7cAjH8LUffabZP8Qu4ysC"
  }
}
```

**Comment by bmuramatsu** [comment]
@dmitrizagidulin this shouldn't be happening, it was an issue, but I thought we fixed it.

**Comment by kayaelle** [comment]
Let's grab the json data to investigate

**Comment by bmuramatsu** [comment]
JSON might be:

{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://w3id.org/security/suites/ed25519-2020/v1",
    "https://w3id.org/dcc/v1",
    "https://w3id.org/vc/status-list/2021/v1"
  ],
  "type": [
    "VerifiableCredential",
    "Assertion"
  ],
  "issuer": {
    "id": "did:key:z6MkhVTX9BF3NGYX6cc7jWpbNnR7cAjH8LUffabZP8Qu4ysC",
    "name": "Example University",
    "url": "https://cs.example.edu",
    "image": "https://user-images.githubusercontent.com/947005/133544904-29d6139d-2e7b-4fe2-b6e9-7d1022bb6a45.png"
  },
  "issuanceDate": "2020-08-16T12:00:00.000+00:00",
  "credentialSubject": {
    "id": "did:key:z6MkhVTX9BF3NGYX6cc7jWpbNnR7cAjH8LUffabZP8Qu4ysC",
    "name": "Kayode Ezike",
    "hasCredential": {
      "type": [
        "EducationalOccupationalCredential"
      ],
      "name": "GT Guide",
      "description": "The holder of this credential is qualified to lead new student orientations."
    }
  },
  "expirationDate": "2025-08-16T12:00:00.000+00:00",
  "credentialStatus": {
    "id": "https://digitalcredentials.github.io/credential-status-playground/JWZM3H8WKU#3",
    "type": "StatusList2021Entry",
    "statusPurpose": "revocation",
    "statusListIndex": 3,
    "statusListCredential": "https://digitalcredentials.github.io/credential-status-playground/JWZM3H8WKU"
  },
  "proof": {
    "type": "Ed25519Signature2020",
    "created": "2022-08-19T06:58:29Z",
    "verificationMethod": "did:key:z6MkhVTX9BF3NGYX6cc7jWpbNnR7cAjH8LUffabZP8Qu4ysC#z6MkhVTX9BF3NGYX6cc7jWpbNnR7cAjH8LUffabZP8Qu4ysC",
    "proofPurpose": "assertionMethod",
    "proofValue": "z33Wy3kvx8UEoPHdQWYHVCXAjW19AZpA88NnikwfJqcH9oNmHyqSkt6wiVS31ewytAX7m2vneVEm8Awo4xzqKHYUp"
  }
}

**Comment by kayaelle** [comment]
This may have had something to do with the document loader being fixed. Assigned to Dmitri to retest.

**Comment by kayaelle** [comment]
@dmitrizagidulin - please retest and let us know if this is fixed.

**Comment by dmitrizagidulin** [comment]
I'm showing it as fixed, having tested it in latest build.
