### ISSUE TITLE
Streamline Issuer Info display

### ISSUE THREAD

**Issue by bmuramatsu** [digitalcredentials/learner-credential-wallet#337]
Currently Issuer Info has as separate sections:
Issuer Name
Location
Issuer URL

Condense to:
Issuer
<issuer name>
<location>
<issuer URL>

**Comment by bmuramatsu** [comment]
what do you think @dmitrizagidulin? if you like it go ahead and assign this to Seth

**Comment by dmitrizagidulin** [comment]
+1 from me (to condense)

**Comment by bmuramatsu** [comment]
this has been implemented, closing
