### ISSUE TITLE
Add help text if camera / QR reader is not visible because LCW doesn't have permissions

### ISSUE THREAD

**Issue by bmuramatsu** [digitalcredentials/learner-credential-wallet#338]
If the user doesn't allow LCW to access the camera, they won't be able to scan a QR code. (duh)

We should display help text if the QR code reader is not available.

To scan a QR code, Learner Credential Wallet needs access to your device's camera. More details (link to https://lcw.app/faq.html#cameraaccess, link doesn't exist yet)

FAQ Text:
Under iOS, Settings > Learner Credential Wallet > toggle Camera on.
Unser Android, Settings > search for Learner Credential Wallet > Permissions > Camera > Allow only while using the app

**Comment by sethduffin** [comment]
Research using the RN method to open app settings and change link.

**Comment by jmcioffi4** [comment]
@bmuramatsu is there a specific text you wanted to use to display on screen that the camera is not available? Such as "Camera access not available. Please allow access in your privacy settings" as a popup with a OK button that takes them back a screen perhaps?

**Comment by bmuramatsu** [comment]
I can't help but think there's some other text that lots of app developers
are using.

I'd prefer text that's meaningful on iOS (Privacy & Security) and Android
(Privacy) settings.

Can we send them to the correct screen to enable access? Something like:
https://stackoverflow.com/questions/52622390/popup-is-not-coming-to-ask-permission-to-access-camera-in-ios-12

**Comment by jmcioffi4** [comment]
PR: https://github.com/digitalcredentials/learner-credential-wallet/pull/502

**Comment by kayaelle** [comment]
This works as expected in iOS and Android.
