### ISSUE TITLE
Ensure the cache is cleared on wallet reset

### ISSUE THREAD

**Issue by sethduffin** [digitalcredentials/learner-credential-wallet#342]
Ensure the cache is cleared for
* Public link
* Credential verification

Edge case: Ensure the light mode settings caries over (make note of this in the code)

**Comment by bmuramatsu** [comment]
@sethduffin is there a way of testing that the cache is cleared?

The lightmode retention works as intended.

**Comment by sethduffin** [comment]
@bmuramatsu I've included testing instructions in the [PR](https://github.com/digitalcredentials/learner-credential-wallet/pull/344), but to answer your question, no - currently there's no way to test this without development access.

**Comment by bmuramatsu** [comment]
Ah, fair enough.

And thanks for that... I'll have to remember to do all the clicks to find the PR from the projects interface...
