### ISSUE TITLE
Build Release Testing

### ISSUE THREAD

**Issue by kayaelle** [digitalcredentials/learner-credential-wallet#348]
Please test credential acceptance flow in prep for new release on android & iOS.

**Comment by bmuramatsu** [comment]
Do you mean test the issues fixed in various Project Iterations to ensure the blocker bugs are fixed? Or do you mean something else?

**Comment by kayaelle** [comment]
Hi @bmuramatsu - this issue is a reflection of the discussion in our weekly call when we discussed the scope of testing. I believe you were referencing blocker bugs to be fixed so that we could complete the build and freeze but we did discuss that there could be iterations and new bugs that would come out of this.

Do you want to list issues that were created as part of this testing so we can track?

**Comment by bmuramatsu** [comment]
Merging [Pull 335](https://github.com/digitalcredentials/learner-credential-wallet/pull/355) means we can build and deploy to public app stores.
