### ISSUE TITLE
Custom Setup, Scan from QR Code not working

### ISSUE THREAD

**Issue by bmuramatsu** [digitalcredentials/learner-credential-wallet#349]
Cannot scan a QR Code to do custom setup.

**Comment by bmuramatsu** [comment]
It's possible we decided to just put the button and not make it functional? @dmitrizagidulin do you recall?

**Comment by dmitrizagidulin** [comment]
@bmuramatsu - I think it was /intended/ to be functional. So, might just be a bug.

**Comment by kayaelle** [comment]
Closing because we removed custom set up.
