### ISSUE TITLE
Test Cases for Learner Credential Wallet

### ISSUE THREAD

**Issue by kayaelle** [digitalcredentials/learner-credential-wallet#354]
Please list step by step procedure that is used to test the LCW. Helpful information for each test case includes:

- test procedure
- actual and expected results
- test data

**Comment by bmuramatsu** [comment]
See: [LCW Acceptance Testing Script](https://docs.google.com/document/d/18k4bHSyIf4lS9mJhVzIjMxxwhBZnDyxAwEv6RcCYGY8/edit)

**Comment by kayaelle** [comment]
Updated label to documentation

**Comment by alexfigtree** [comment]
Needs to be added to LCW docs folder

**Comment by alexfigtree** [comment]
Closing this and opening this: https://github.com/digitalcredentials/learner-credential-wallet/issues/579
