### ISSUE TITLE
Bottom nav share Create Public Link triggers Send Credential Workflow

### ISSUE THREAD

**Issue by bmuramatsu** [digitalcredentials/learner-credential-wallet#361]
When sharing from the bottom nav share (build 55) and Creating a Public Link. LCW triggers the "Sending Credential" workflow (or at least display of Sending Credential) after successfully Creating the Public Link. Need to force quit the app to get it to respond.

To reproduce use a verified credential (to allow Create Public Link to work), add to LCW, from the bottom nav initiate "Create Public Link", select the credential, acknowledge you want to proceed, LCW should create the link (you can see it in the background) but you should see the "Sending Credential" dialog and lock the app.

(Note we updated the text to the warning modal, perhaps this triggered some other change.)

**Comment by bmuramatsu** [comment]
Note that the error is only happening on my iPhone with Build 55. I wait at least 10 seconds with the Sending Credential dialog before choosing to force quit the app. On Android, Build 55, I see the dialog but it clear off within 1 second.

The same bug does NOT occur when Creating a Public Link from the 3 dot menu from Credential Preview.

**Comment by dmitrizagidulin** [comment]
ok, so for me, on Android, seemed to work ok (as expected).
My repro steps:
1. Added a VC to the wallet
2. Went into VC detail from the home screen. Three-dot-menu then created public link.
3. Then initiated Share from bottom menu
4. Pressed 'Send a credential', selected the credential, clicked 'Send Selected Credential' button
5. Got taken to 'Share Preview' screen, hit Send
6. OS share sheet popped up (as expected).

**Comment by dmitrizagidulin** [comment]
@bmuramatsu - I can reproduce it on iOS also (also locks up, for me).
1. Add a VC to the wallet
2. Go to Home, then select Share icon from bottom menu
3. Select 'Create a public link' button at the top
4. Select the VC. 'Are you sure?' confirmation comes up, hit 'Create Link'
5. Auto-triggers 'Sending Credential...' and hangs.

**Comment by kayaelle** [comment]
@bmuramatsu @dmitrizagidulin - what are the next steps for this?

**Comment by kayaelle** [comment]
Ignore comment - question - realized it's closed.
