### ISSUE TITLE
What's an integration readmap?

### ISSUE THREAD

**Issue by wowkalucky** [digitalcredentials/learner-credential-wallet#364]
# What's an integration readmap?

## Context

A brand new verifiable credential Issuer wants to support LCWallet.

## Questions

1. What are the integration prerequisites?
2. Are there development mobile applications builds to use during the integration development?
4. Issuers Registry extension?
5. How is the `issuerAuthRegistry` maintained?

Couldn't find any related info for those. Please, point if any.
Thanks.

**Comment by dmitrizagidulin** [comment]
@wowkalucky thanks for the heads up! We'll get back to you with the answers shortly.

**Comment by dmitrizagidulin** [comment]
@wowkalucky Apologies for the delay. I know your team has finished integration -- is there anything else we can answer?

**Comment by kayaelle** [comment]
Hey @wowkalucky - we're going to close this issue for now but feel free to re-open and reach out if we can be of assistance.

**Comment by wowkalucky** [comment]
Thanks @dmitrizagidulin @kayaelle . We have  settled everything.
