### ISSUE TITLE
Cannot send multiple credentials

### ISSUE THREAD

**Issue by kayaelle** [digitalcredentials/learner-credential-wallet#369]
From Pivotal list

Labels: none

status: finished

created Dec 5, 2022

by Brandon

Description: Using mock crendentials loaded from About screen.

Use bottom nav to Share
Select Send Credential(s)
Select GT Guide and Ian Malcom Student ID
From Share Preview screen cannot "Send" credentials.

Note: Both credentials are not verified, perhaps that's getting in the way of Sending. (I recall having disussed this but not sure if we implemented anything about it.)

**Comment by bmuramatsu** [comment]
This was fixed. 

LCW doesn't allow non-verified credentials to be Shared (sent or create public link). Rudimentary error messages, could improve them.
