### ISSUE TITLE
Add error message if we can't Create Public Link (or Add to LinkedIn Profile) if credential is not verified.

### ISSUE THREAD

**Issue by kayaelle** [digitalcredentials/learner-credential-wallet#376]
From Pivotal list

Labels: none

status: unstarted

created Dec 15, 2022

by Brandon

Description: #298 

If a credential is not verified but the user tries to Create Public Link, we're preventing them from doing so (intentiionally or unintentionally)

Instead of the "Are you sure?" warning. Create a new warning.

You can only create a public link for a verified credential. Please ensure the credential is verified before trying again.

**Comment by bmuramatsu** [comment]
duplicate, closing as original is closed
