### ISSUE TITLE
Delete profile with credentials after viewing detail wrong back screen

### ISSUE THREAD

**Issue by kayaelle** [digitalcredentials/learner-credential-wallet#381]
From Pivotal list

Labels: none

status: unstarted

created Dec 15, 2022

by Brandon

Description: #305

Settings > Manage Profiles > select a profile with credentials three dot menu > Delete > Details

After viewing Details returns to manage profile screen not the modal with the Cancel and Delete Profile option.

**Comment by bmuramatsu** [comment]
duplicate, closing
