### ISSUE TITLE
Add from pasted JSON, invalid JSON error warning needs updating

### ISSUE THREAD

**Issue by kayaelle** [digitalcredentials/learner-credential-wallet#382]
From Pivotal list

Labels: none

status: unstarted

created Dec 15, 2022

by Brandon

Description: #303

Pasting invalid JSON on Add Credential screen, error message is for "Add from file". 

Ensure the JSON contains one or more supported credentials.

**Comment by bmuramatsu** [comment]
Duplicate, closing
