### ISSUE TITLE
Prevent "create public share" if the credential cannot be verified and has never been verified.

### ISSUE THREAD

**Issue by kayaelle** [digitalcredentials/learner-credential-wallet#387]
From Pivotal list

Labels: none

status: unstarted

created Sep 2, 2022

by Brandon

Description: #312

Prevent "create public share" if the credential cannot be verified and has never been verified.

Give the user a warning: "This credential is not verifiable and we do not recommend sharing it publicly."

Once we get caching in place for the verification status, if the credential has never been verified then don't allow sharing. If the credential has been verifiable 80% of the time then allow sharing with the following warning. "This credential is not currently verifying, but has been verifiable in the past. You may not want to share it publicly as others may not be able to verify its status."

**Comment by kayaelle** [comment]
#312 is closed

**Comment by bmuramatsu** [comment]
duplicate, closing
