### ISSUE TITLE
Import / Restore Refactor

### ISSUE THREAD

**Issue by kayaelle** [digitalcredentials/learner-credential-wallet#389]
From Pivotal list

Labels: none

status: unstarted

created Sep 1, 2022

by Brandon

Description: Import / restore should be refactored as effectively a single function that knows about all DCC json types and works accordingly. Goal to reduce overhead on the user to know whether they have the right file.

Discuss before implementing:

Example: Trying to restore profile...You've selected a wallet file containing one or more profiles. Would you like to restore your wallet overwriting everything with double confirmation.

**Comment by alexfigtree** [comment]
Dmitri recommends closing and revisiting later if it comes up.
