### ISSUE TITLE
Custom Setup should have a "Create default profile" feature (Discuss)

### ISSUE THREAD

**Issue by kayaelle** [digitalcredentials/learner-credential-wallet#390]
From Pivotal list

Labels: none

status: unstarted

created Dec 5, 2022

by Brandon

Description: Following the Custom setup route, a user should be able to create a wallet just as if they followed the quick setup. Yes, they can cancel their way out of it, but I think we should add a create default wallet option.

Not sure which order the button should be listed in. Open to discussion of the feature in general.

**Comment by dmitrizagidulin** [comment]
I think this issue can be closed, since we've removed the Custom Setup functionality.
