### ISSUE TITLE
Encrypted Backup Issues

### ISSUE THREAD

**Issue by kayaelle** [digitalcredentials/learner-credential-wallet#395]
From Pivotal list

Labels: none

status: unstarted

created Dec 15, 2022

by Brandon

Description:

**Comment by bmuramatsu** [comment]
Duplicate of https://github.com/digitalcredentials/learner-credential-wallet/issues/302

**Comment by bmuramatsu** [comment]
Duplicate of https://github.com/digitalcredentials/learner-credential-wallet/issues/394
