### ISSUE TITLE
'Select to Speak' accessibility control on Android causes bottom nav row to disappear

### ISSUE THREAD

**Issue by kayaelle** [digitalcredentials/learner-credential-wallet#405]
From Pivotal list

Labels: none

status: unscheduled

created Dec 22, 2021

by Dmitri

Description: To test (on Android):

1. Go to Settings > Accessibility > enable 'Select to Speak'.  (This adds an accessibility icon to the bottom phone nav part of the screen (alongside the usual 3 android icons).
2. On any eduWallet screen (like home screen), tap the select to speak icon, tap the Play button, which reads the screen.
3. Close the 'select to speak' audio controls.

The 4 app nav icons (home/share/add/settings) disappear. The blank areas of the nav bar still work if you tap on them, and their accessibility text gets read. But the icons disappear.

**Comment by alexfigtree** [comment]
The 4 app nav icons (home/share/add/settings) are now longer disappearing with "Select to Speak" functionality on Android. Moving to Release Ready.

**Comment by alexfigtree** [comment]
Working now, moving to Done
