### ISSUE TITLE
Remove OIDC List

### ISSUE THREAD

**Issue by kayaelle** [digitalcredentials/learner-credential-wallet#408]
Currently listing pilot issuers using OIDC in the wallet. This config needs to be moved out of the wallet. Discuss refactoring.

**Comment by bmuramatsu** [comment]
To move OIDC out of LCW, we'd need to put the OIDC issuer list in an encrypted server location and maintain that.

**Comment by kayaelle** [comment]
Research list to see if anyone still needs to be on this list or if they are old pilots.

**Comment by dmitrizagidulin** [comment]
This has been completed as of PR #538.

**Comment by dmitrizagidulin** [comment]
Released to stores as `v2.0.19-build74`
