### ISSUE TITLE
Support for alternate persistent web URL for public shares

### ISSUE THREAD

**Issue by bmuramatsu** [digitalcredentials/learner-credential-wallet#414]
LCW assumes that a credential doesn't have a persistent web URL for a public view of a credential. Allow the user to specify a public share at VerifierPlus or an alternate site (i.e., Credly has public URLs for their credentials, allow that to be added / displayed from the credential)

**Comment by kayaelle** [comment]
Needed to support assertion urls that could be included in OBv3

**Comment by kayaelle** [comment]
@bmuramatsu - to clarify, if an assertion url is provided in the credential (located in the VC id), then the user can choose to share this link in addition to creating a public link on verifierplus?

**Comment by brandonopened** [comment]
is this the same issue as me wanting to add badges to my learner credential wallet but I can't? public URL: https://www.credly.com/badges/ff086945-65e2-4079-a54c-9d17b5dfe4b4/public_url 

it feels like supporting open badge wallets so people can import credentials would be quite useful.

**Comment by bmuramatsu** [comment]
> @bmuramatsu - to clarify, if an assertion url is provided in the credential (located in the VC id), then the user can choose to share this link in addition to creating a public link on verifierplus?

I think this is up to us to decide. This gets complex fast if we allow the user to select which link they want to share.

- Allowing users to share either link would require more UI/UX work...might be as straightforward as adding another block to the Share screen for Share existing link (though this assumes only one link, or the first link parsed in JSON for MVP) with it's own add to LinkedIn Profile grouped together; and retaining the create public link and separate add to LinkedIn Profile grouped together in it's own block.
- Just allow users to share an existing link if it exists, remove the unshare link button, and potentially adjust the Add to LinkedIn Profile button.

**Comment by alexfigtree** [comment]
Dmitri: Partially addressed by #542.

**Comment by alexfigtree** [comment]
@dmitrizagidulin Says issue has been fully addressed by #542 and can close
