### ISSUE TITLE
Add Learner Credential Wallet text to first open screen

### ISSUE THREAD

**Issue by kayaelle** [digitalcredentials/learner-credential-wallet#429]
The open screen only displays a folder.  Add text" Learner Credential Wallet" below it.

**Comment by kayaelle** [comment]
<img width="414" alt="signal-2023-05-02-163358" src="https://user-images.githubusercontent.com/206059/235779885-61abfc7e-65a9-4689-a7de-0bf0ba112ecb.png">

Labeling as "needs design" but it should be a quick review to add centered text below the folder icon.

**Comment by bmuramatsu** [comment]
I think the text looks good on iOS and Android LCW v2.0.11-Build 66 on Moto g and iPhone 13 Pro.
