### ISSUE TITLE
Replace verifier url with env variable that works with ios & android

### ISSUE THREAD

**Issue by kayaelle** [digitalcredentials/learner-credential-wallet#431]
Currently verifierplus.org is hardcoded in the app so that it may be used when creating links. 

For iOS can use info.plist: https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/AboutInformationPropertyListFiles.html

preferences.xml for android?

**Comment by kayaelle** [comment]
context: LCW is reference implementation software and should be usable with any version of VerifierPlus not just the DCC hosted one.

@dmitrizagidulin - do you have thoughts on best approach beyond info.plist and preferences.xml that's suggested above?

**Comment by dmitrizagidulin** [comment]
This has been completed as part of issue #542
