### ISSUE TITLE
Android blue `add` button doesn't click / doesn't add credential to wallet

### ISSUE THREAD

**Issue by jmcioffi4** [digitalcredentials/learner-credential-wallet#449]
Steps to reproduce:
1 - open app
2 - click add credential on home screen
3 - type in a valid badge/credential
4 - try to click `add`
5 - notice it clicks and goes through on iOS, but it doesn't seem to click on Android

I've noticed it just re-clicks the text box to type on android rather than clicking `add`

does not show in dev logs

found on : emulators (iOS and Android)

**Comment by jmcioffi4** [comment]
UPDATE:
fixed with PR: https://github.com/digitalcredentials/learner-credential-wallet/pull/450

**Comment by bmuramatsu** [comment]
Appears to work as intended, Add button works. Tested with JSON from BCSI August 16 credential. Followed steps to reproduce, on (3) pasted the JSON and clicked Add and the credential was added.

(Need to test with a URL as that field supports adding by URL.)

**Comment by kayaelle** [comment]
@bmuramatsu - please try this url in android: https://raw.githubusercontent.com/digitalcredentials/docs/main/example-credentials/criteria-markdown-bold/credential.json 

Thanks

**Comment by bmuramatsu** [comment]
Works as expected in Android LCW v2.0.11-Build 66. Can add credential from URL with JSON using instructions provided.

**Comment by kayaelle** [comment]
Great - thanks @bmuramatsu! @jmcioffi4 - we're good on this.
