### ISSUE TITLE
Add Markdown support for select OBv3 fields

### ISSUE THREAD

**Issue by bmuramatsu** [digitalcredentials/learner-credential-wallet#456]
Per the OBv3 specification, some of the fields we display in LCW and VerifierPlus should support Markdown.

Add Markdown support for:
- Criteria.Narrative (aka our Criteria field)

We _may_ want to add Markdown support for this field, even though it's not currently in the spec.
- Achievement.Description (aka our Description field, )

Note: We'll want to consider sanitizing the URL in particular and Markdown generally. Probably less important for the initial implementation as we know all the users of our software.

**Comment by kayaelle** [comment]
For now, let's add sanitized markdown for these narrative properties that are indicated in the OBv3 spec: 

- Criteria.narrative: https://1edtech.github.io/openbadges-specification/ob_v3p0.html#org.1edtech.ob.v3p0.criteria.class
- Evidence.narrative: https://1edtech.github.io/openbadges-specification/ob_v3p0.html#evidence

**Comment by kayaelle** [comment]
@bmuramatsu - it should be in criteria.narative - we can check. We should also check that our issuing templates are using criteria.narrative too.

**Comment by kayaelle** [comment]
Please note that I've removed evidence.narrative from this issue. It will only be for criteria.narrative. We will create a separate issue for adding evidence to the display.

**Comment by bmuramatsu** [comment]
This appears to work as intended on iOS and Android v2.0.9-build 64 for italic, bold, unordered, hyperlink and ordered list.

**Comment by bmuramatsu** [comment]
Continues to work as intended on iOS and Android LCW v2.01.11-Build 66.
