### ISSUE TITLE
Add 'Register Wallet' installation step

### ISSUE THREAD

**Issue by dmitrizagidulin** [digitalcredentials/learner-credential-wallet#457]
Create a new (optional) installation wizard step, that opens a URL (in the user's default web browser) to the 'Register this wallet with your browser' page.

The button will open: `https://lcw.app/register-wallet.html` 

This enables LCW to be used with CHAPI's wallet selector.

**Comment by kayaelle** [comment]
CHAPI reference: https://chapi.io/

**Comment by jmcioffi4** [comment]
PR Created: https://github.com/digitalcredentials/learner-credential-wallet/pull/488

**Comment by dmitrizagidulin** [comment]
Register step added, closing.

**Comment by alexfigtree** [comment]
Keeping open until after deployment

**Comment by alexfigtree** [comment]
Dmitri says it has been deployed (months ago)
