### ISSUE TITLE
Open Badges Display Question

### ISSUE THREAD

**Issue by kayaelle** [digitalcredentials/learner-credential-wallet#458]
In:

https://github.com/digitalcredentials/learner-credential-wallet/blob/main/app/lib/credentialDisplay/openBadgeCredential.tsx

there's a few of fields I'm unclear on:

- subjectName: is this the full name of the earner? In an example badge we put together We had "name" in the achievementSubject. Is that what this is?
- numberOfCredits: is this AcheivementSubject.creditEarned?
- Are we displaying the criteria.narrative in criteria?

Is there a file that translates the OB fieldnames to those in this file? 

Do we want to take the time to add logic looking for any OB field and how to display it if it is present *in addition to the required fields"? 

I'm going to tag @dmitrizagidulin and @jchartrand for help with these questions. We have a couple of LCW issues awaiting instructions based on this one. Thanks!

**Comment by kayaelle** [comment]
@bmuramatsu do you know what credentials used: numberOfCredits?

If not, any objections to us removing it from LCW so that we can get more aligned with OBv3?

**Comment by dmitrizagidulin** [comment]
> * subjectName: is this the full name of the earner? In an example badge we put together We had "name" in the achievementSubject. Is that what this is?

Yes, that's the full name of the earner. Which means we need to sort out the issue of where a name goes, with the OBv3 group.

> * numberOfCredits: is this AcheivementSubject.creditEarned?

I believe so, yes.

> * Are we displaying the criteria.narrative in criteria?

It seems that the BCSI example credential had a criteria narrative?

> Is there a file that translates the OB fieldnames to those in this file?

No, that's not quite how it works. 
 
> Do we want to take the time to add logic looking for any OB field and how to display it if it is present *in addition to the required fields"?

Not sure! That may be a decent future roadmap item.

**Comment by bmuramatsu** [comment]
> > * Are we displaying the criteria.narrative in criteria?
> 
> It seems that the BCSI example credential had a criteria narrative?

From the way I read the OBv2 spec, I would have expected there to be text in the criteria field or the  criteria.narrative field but not both. 

The way the BCSI OBv2 credential reads to me, is there's an artificial distinction between what's included in criteria and criteria.narrative. I am recommending to them that they combine that text together. (I can't see how it should be distinct given what I've read in OBv2 and OBv3.)

I'd certainly love to hear from this group if we think it goes in the criteria field or the criteria.narrative field. (Or for whatever reason it's something else!)

 > > Do we want to take the time to add logic looking for any OB field and how to display it if it is present *in addition to the required fields"?
> 
> Not sure! That may be a decent future roadmap item.

I think this is a potentially big issue as well. The JSON and schema are not so tightly described (I think) that there's not going to be interpretation on what to include where and how to render it. Arbitrary rendering will get challenging, potentially very challenging.

It's important to note / recall that we're passing through the original json (and fields) even if LCW and VerifierPlus are not rendering them.

**Comment by bmuramatsu** [comment]
> @bmuramatsu do you know what credentials used: numberOfCredits?
> 
> If not, any objections to us removing it from LCW so that we can get more aligned with OBv3?

I think we had it because we thought issuers would want to display it. If there's a better place to put that information, we should match the spec. 

We haven't had a request to include data nor display it so it's _fine to remove for now_. I suspect it will come up in a future use case.

**Comment by kayaelle** [comment]
Thanks @bmuramatsu. 

We could remove numberOfCredits for now and then have a task to add all OBv3 fields if they are included in the badge . We may decide we won't want to do this... because it could be too much for the screen but if we print as PDF, we'll need all of the fields in the code somewhere.

re: OBv2 and criteria - I see what you mean by criteria and criteria.narrative: https://www.imsglobal.org/sites/default/files/Badges/OBv2p0Final/examples/index.html#Criteria

It looks like the content for criteria should be in narrative for OBv3.

Sidebar: we're working on a schema for degree at vc-edu that will hopefully get into OBv3. If not, we'll put properties in a vc-edu @context as a stop gap. Doing our best to engage with the community on this to find as much cohesion as possible.

**Comment by kayaelle** [comment]
We'll have to keep subjectName to accommodate SJCC & CU credentials....

**Comment by kayaelle** [comment]
Created this issue to update display for OBv3 in the LCW: https://github.com/digitalcredentials/learner-credential-wallet/issues/460

Additional fields such as earners name and evidence will be added as separate issues.
