### ISSUE TITLE
Open Badges 3.0 Display

### ISSUE THREAD

**Issue by kayaelle** [digitalcredentials/learner-credential-wallet#460]
This issue explains which Open Badges 3.0 fields the LCW should display if a Verifiable Credential also contains the type: "AchievementCredential" or "OpenBadgeCredential".  The list of fields begins here:

https://1edtech.github.io/openbadges-specification/ob_v3p0.html#achievementcredential

Required properties are bolded. Otherwise, display only if the value exists.

- AchievementCredential.name (currently called "title" in the LCW) **Required** 
- Achievement.image (https://1edtech.github.io/openbadges-specification/ob_v3p0.html#achievement) - already being displayed

Issuer Information (https://1edtech.github.io/openbadges-specification/ob_v3p0.html#org.1edtech.ob.v3p0.profile.class)

This already looks ok in the LCW but noting here anyway for requirements purposes:

- profile.name (**Required** )
- If exists: profile.image, profile.url
- On Issuer info screen: profile.name(**Required** ), profile.address (location header), profile.url, Registries list

- Issuance date: AchievementCredential.issuanceDate (https://1edtech.github.io/openbadges-specification/ob_v3p0.html#achievementcredential) (**Required** )

- Expiration date: AchievementCredential.expirationDate (https://1edtech.github.io/openbadges-specification/ob_v3p0.html#achievementcredential) - should already be displayed if there is one.

- Achievement.type ( https://1edtech.github.io/openbadges-specification/ob_v3p0.html#achievement). This is a new field for the LCW. We can label it "Achievement Type". Example: **Achievement Type** Certificate

- Achievement.description (https://1edtech.github.io/openbadges-specification/ob_v3p0.html#achievement) (**Required** )  - already being displayed

- Achievement.criteria.narrative (https://1edtech.github.io/openbadges-specification/ob_v3p0.html#achievement) (**Required** ) - this is a markdown field that is already being displayed but the markdown doesn't get rendered. See issue #456

**Comment by kayaelle** [comment]
Some test credentials can be found here: https://github.com/jchartrand/dcc-test-creds/tree/main

We will make more.

**Comment by lautom36** [comment]
@kayaelle - So just to clarify we are creating a new credential display for type AchievementCredential and then adding the missing fields on OpenBadgeCredential?

**Comment by kayaelle** [comment]
@lautom36 - AchievementCredential and OpenBadgeCredential are synonymous in the OBv3 spec. As a reference from the schema (https://purl.imsglobal.org/spec/ob/v3p0/schema/json/ob_v3p0_achievementcredential_schema.json): "  "type" : {
      "oneOf" : [ {
        "description" : "The value of the type property MUST be an unordered set. One of the items MUST be the URI 'VerifiableCredential', and one of the items MUST be the URI 'AchievementCredential' or the URI 'OpenBadgeCredential'.",

What we should do is look for both and then display the same fields for both so that when you add the missing fields for "OpenBadgeCredential" they display for both.

**Comment by bmuramatsu** [comment]
@kezike I'll add you one better, how does the wallet choose between VC entries and OBv3 entries that may appear at multiple levels!

**Comment by kayaelle** [comment]
Right now the wallet is hardcoded for Open Badges 3.0. We should look into scenarios where the credential could differ from OBv3 but not for this issue. Will create a follow-up issue.

**Comment by kayaelle** [comment]
> @kayaelle One thing that has confused me for a while now is the presence of `name`, `description`, and `image` at multiple levels of the credential. In the event that `name`, `description`, or `image` appear both at the root level of the credential _and_ at `credentialSubject.achievement`, how should the wallet handle that?

I think this is confusing too. The name, description, and image are intended to be specific to the VC that was issued whereas the `credentialSubject.achievement` is intended to be the generic description that applies to anyone that the badge was issued to. Up for discussion could be prioritizing the root level over the credentialSubject.achievement content.

I think this is a related but different discussion about prioritizing fields in VCs versus OB3. I'll make an issue for discussion. Note that currently this wallet is only displaying Open Badges fields.

**Comment by kayaelle** [comment]
Re-opening to find PR related to his issue.
