### ISSUE TITLE
New Mock Credentials Planning

### ISSUE THREAD

**Issue by kayaelle** [digitalcredentials/learner-credential-wallet#466]
Planning for new mock credentials is in this document: [https://docs.google.com/document/d/16zvVaRNGR9-0pbOq9P9WK6snY6KDEh2_vruX6FLM1uM/edit](https://docs.google.com/document/d/16zvVaRNGR9-0pbOq9P9WK6snY6KDEh2_vruX6FLM1uM/edit)

Please add your ideas and content before **August 4**

**Comment by alexfigtree** [comment]
Closing this in favor of https://github.com/digitalcredentials/learner-credential-wallet/issues/571
