### ISSUE TITLE
Share Credential (Beta) Screen URL field and Copy Button

### ISSUE THREAD

**Issue by bmuramatsu** [digitalcredentials/learner-credential-wallet#467]
In both iOS and Android v2.0.9 Build 64, 

The copy button and URL field are no longer appropriately designed.

Android build has URL field that spans 40% of the width and Copy button that spans 60% of the width.
<img src="https://github.com/digitalcredentials/learner-credential-wallet/assets/752326/2722c4e0-1673-4d54-8976-c5f2f5420c41" width=30%> )

iOS build has URL field that spans 40% of the width and Copy button that spans 20% of the width with a 40% wide gap of empty space to the right.

<img src="https://github.com/digitalcredentials/learner-credential-wallet/assets/752326/d747850c-8aad-47c2-9bfe-83fc86f5d299" width=30%>

From build 2.0.7-build 62, this is what the screen is supposed to look like.
<img src="https://github.com/digitalcredentials/learner-credential-wallet/assets/752326/385f1ef1-d381-4bff-8ece-9fef369cbef1" width=30%>

To reproduce. Take any credential and add it to LCW. Select the 3 dot menu > Share > Create Public Link.

To confirm if fixed:
- Check to make sure the iOS and Android builds look identical
- Check to make sure the Copy button is appropriately sized and flush with the right hand margin (aka other buttons)
- Check to make sure the URL filed is appropriately sized, wider than the copy button, flush with the left hand margin, and the appropriate space between it and the Copy button

**Comment by kayaelle** [comment]
Confirmed in android too
