### ISSUE TITLE
Android Add to LinkedIn shortcut puts incorrect "Issuing Organization"

### ISSUE THREAD

**Issue by bmuramatsu** [digitalcredentials/learner-credential-wallet#469]
In Android (not iOS) v2.0.9-build 64, when a user selects "Add to LinkedIn Profile" from any credential, an odd "Issuing Organization" is added to the template.

This feature works as intended in iOS.

In iOS if the issuer in LCW is Bioscience Core Skills Institute, the correct text is placed in the field when writing to the LinkedIn shortcut.

In Android, regardless of the issuer in LCW, United Latino Students Association is populated by default in the field in the LinkedIn "add license or certification" screen.

### Two examples from Android with incorrect data in Issuing Organization field

Documentation and SOP, Issuing institution should read "Bioscience Core Skills Institute"
<img src="https://github.com/digitalcredentials/learner-credential-wallet/assets/752326/ad5cd7a5-f8b4-428c-acbb-a2d406b09697" width=30%>

GT Guide, Issuing institution should read "Example University":
<img src="https://github.com/digitalcredentials/learner-credential-wallet/assets/752326/c32dda7c-a7c7-486d-9be7-0cd999b80fbe" width=30%>

### Correct display in iOS
<img src="https://github.com/digitalcredentials/learner-credential-wallet/assets/752326/e39176c3-e0de-4432-a907-1dadbbfc6cb0" width=30%>

Attached is the Documentation and SOP credential used to generate the differing display.

To reproduce: Add the attached credential to LCW in Android, select 3 dot menu, Share, Add to LinkedIn, note the Issuing Organization mismatch with the Issuer in the credential.

To confirm if fixed: Add a credential to LCW, select 3 dot menu, Share, Add to LinkedIn, see if the Issuing Organization in the LinkedIn form matches the Issuer in the credential.

[Android LinkedIn Wrong Issuing Organization Test Credential.txt.zip](https://github.com/digitalcredentials/learner-credential-wallet/files/12241829/Android.LinkedIn.Wrong.Issuing.Organization.Test.Credential.txt.zip)

**Comment by jmcioffi4** [comment]
Using their documentation found here ( https://addtoprofile.linkedin.com ) there is some dummy data you can use to test the devices with. on iOS using the link ( https://www.linkedin.com/profile/add?startTask=CERTIFICATION_NAME&name=Test%20Certificate&organizationName=LinkedIn&issueYear%20=2018&issueMonth=2&expirationYear=2020&expirationMonth=5&certUrl=https%3A%2F%2Fdocs.%20microsoft.com%2Fen-us%2Flearn%2Fcertifications%2Fd365-functional-consultant-sales&certId=1234 ) to manually test outputs 

![Image](https://github.com/digitalcredentials/learner-credential-wallet/assets/59583650/41dc0310-197a-442b-9c98-dd84d08e25c5)

and using the same link on android outputs

![Image](https://github.com/digitalcredentials/learner-credential-wallet/assets/59583650/ed0aed53-597e-4672-9231-53f21db176a7)

where as the real data that should output is 

![Image](https://github.com/digitalcredentials/learner-credential-wallet/assets/59583650/4776c95d-a55e-4d1e-ad41-b1de12b8e2b2)

**Comment by alexfigtree** [comment]
Could potentially reach out to someone at LinkedIn about this in the future.

**Comment by wantaekchoi** [comment]
Any updates on this issue? It would be great to know if a fix or workaround is being considered.

**Comment by alexfigtree** [comment]
@wantaekchoi This is more of a LinkedIn issue, and we haven't heard anything on their end about it. They don't allow a free form text field for the issuer, so we will need to close this issue.
