### ISSUE TITLE
Credential with issuer not in registry, selecting Issuer crashes LCW

### ISSUE THREAD

**Issue by bmuramatsu** [digitalcredentials/learner-credential-wallet#471]
Credential, with issuer not in registry, crashes LCW in iOS and Android v2.0.9-build 64.

I'm not sure where the problem may lie. Might be because the issuer isn't in a registry or something to do with the test credential itself.

To reproduce:
- Add test credential from one of the set Kayode put together, namely [criteria-markdown-combo](https://github.com/digitalcredentials/docs/tree/add-example-credentials/example-credentials/criteria-markdown-combo)
- Preview the credential you added
- Select the Issuer name from the Credential Preview screen, LCW crashes

To confirm if fixed: Should be able to add test credential from Kayode's set, with an issuer not in a registry and see the details

**Comment by jmcioffi4** [comment]
After attempting to replicate I found the following:
- Android will crash when clicking on issuer, I think this may be related to the issue I found here: https://github.com/digitalcredentials/learner-credential-wallet/issues/496
- iOS does **not** crash

**Comment by jmcioffi4** [comment]
Update: after doing a fresh pull of main today (commit [7175555](https://github.com/digitalcredentials/learner-credential-wallet/commit/71755552744b3f0041495a3024752ca52c1aac44)) and a fresh run of npm install and can no longer replicate

**Comment by kayaelle** [comment]
Closing for now. Thanks!
