### ISSUE TITLE
Markdown render wrong color on Dark Mode

### ISSUE THREAD

**Issue by dmitrizagidulin** [digitalcredentials/learner-credential-wallet#480]
In Dark Mode, the Markdown render component is black text on dark background:

![image](https://github.com/digitalcredentials/learner-credential-wallet/assets/947005/ba5fddd2-8d61-4b75-a53d-579fd1c005b9)

**Comment by jmcioffi4** [comment]
Could you link to the JSON for this credential please? In the meantime will try to find another credential to test this with.

**Comment by bmuramatsu** [comment]
Displays as expected in iOS and Android LCW v2.0.11-Build 66–unordered list bullets are visible as expected in both dark mode and light mode using BCSI test credential.

Also works as intended in both iOS and Android LCW v2.0.11-Build 66-ordered lists, italics, bold are visible as expected in both dark mode and light mode using this [test credential](https://github.com/digitalcredentials/docs/blob/main/example-credentials/criteria-markdown-numbered-list/credential.json.qr.gif).
