### ISSUE TITLE
Achievement Type Credential Details Screen Not Displaying Correct Content

### ISSUE THREAD

**Issue by kayaelle** [digitalcredentials/learner-credential-wallet#482]
Achievement Type always displays "Achievement" vs the content in: achivement.AchievementType

**Comment by lautom36** [comment]
I would guess that we are pullingachievement.type not achievement.achievementType

**Comment by jmcioffi4** [comment]
PR: https://github.com/digitalcredentials/learner-credential-wallet/pull/483

**Comment by bmuramatsu** [comment]
Appears to display as expected in Android and iOS LCW v2.0.11-Build 66. `achievement.achievementType` is displayed as expected on screen.
