### ISSUE TITLE
Display of achievementType

### ISSUE THREAD

**Issue by bmuramatsu** [digitalcredentials/learner-credential-wallet#485]
Related to [LCW Issue 90](https://github.com/digitalcredentials/web-verifier-plus/issues/90).

Display of `achievementType` should be consistent between LCW and VerifierPlus.

In LCW v2.0.11-Build 66, `achievementType` is displayed underneath Expiration Date. In VerifierPlus, it's displayed underneath the credential name.

I prefer it underneath the credential name as in VerifierPlus, the achievementType is somewhat related to the credential name.

**Preferred Display** (disregard `achievementSubject.name`)
<img src="https://github.com/digitalcredentials/learner-credential-wallet/assets/752326/fe5bd425-03b2-431b-af22-458ab109d24a" width=30%>

**Comment by jmcioffi4** [comment]
PR Created: https://github.com/digitalcredentials/learner-credential-wallet/pull/497

**Comment by kayaelle** [comment]
Looks good in LCW (ios & android) and VerifierPlus.
