### ISSUE TITLE
Display of Issuance Date and Expiration Date should be consistent between LCW and VerifierPlus

### ISSUE THREAD

**Issue by bmuramatsu** [digitalcredentials/learner-credential-wallet#486]
I prefer the display on VerifierPlus where the Issuance Date and Expiration Date are on the same row.

**Preferred Display**
<img src="https://github.com/digitalcredentials/learner-credential-wallet/assets/752326/c6ed52ab-41f2-4411-8eb6-8f742538ea3a" width=30%>

**Comment by jmcioffi4** [comment]
PR Created: https://github.com/digitalcredentials/learner-credential-wallet/pull/495
