### ISSUE TITLE
Bottom Nav Share, "Create a public link" displays "GT Guide" onscreen after creating the link.

### ISSUE THREAD

**Issue by bmuramatsu** [digitalcredentials/learner-credential-wallet#490]
Occurs in LCW v2.0.11-build 66 on iOS and Android.

(I can't find "GT Guide" text in the JSON of the all the credentials I've tried, nor did a search in the repo turn up anything except for inside mock credentials.) Attached is a credential where one can see the issue.

To reproduce:

- Add a credential to LCW
- From the bottom nav, select the share icon
- Select "Create a public link"
- Select (any) credential, and "Create Link" from the "Are you sure?" modal
- Note GT Guide at the top of the interstitial screen when the Public Link is getting created and on the resulting Public Link (Beta) screen.

**Bottom Nav, Share Screen**
<img src="https://github.com/digitalcredentials/learner-credential-wallet/assets/752326/85636560-4951-4d8d-addf-3bbeaa7bc97c" width=30%>

**Interstitial as Public Link getting created—Note GT Guide**
<img src="https://github.com/digitalcredentials/learner-credential-wallet/assets/752326/f1c2c20e-26fd-4b48-ae65-2bfee935d1a9" width=30%>

**Resulting Public Link screen—Note GT Guide**
<img src="https://github.com/digitalcredentials/learner-credential-wallet/assets/752326/6714e92b-b025-4246-aa63-763cee4e08a6" width=30%>

**Comment by kayaelle** [comment]
Checking on credential name display

**Comment by kayaelle** [comment]
"GT Guide" displays no matter what the credential name is. Please change so that the credential name of the chosen credential is displayed.

**Comment by kayaelle** [comment]
Confirm that the chosen credential name displays (instead of GT GUIDE)  in both ioS and android
