### ISSUE TITLE
Verification on iOS and Android are not the same (LCW)

### ISSUE THREAD

**Issue by jennacioffi** [digitalcredentials/learner-credential-wallet#496]
![Screenshot 2023-08-23 at 9 44 51 AM](https://github.com/digitalcredentials/learner-credential-wallet/assets/59583650/2243ea76-53b4-4dd4-859a-c1cfaf40f6d6)

Used credential: https://github.com/digitalcredentials/docs/blob/main/example-credentials/criteria-markdown-bold/credential.json
iOS states verified while Android states Not Verified

**Comment by alexfigtree** [comment]
Dmitri is fairly sure it's been fixed but we should retest

**Comment by alexfigtree** [comment]
Re-tested, Android now correctly showing Verified status, icon, etc.. Closing ticket.
