### ISSUE TITLE
Edit instruction text under "Send a credential"

### ISSUE THREAD

**Issue by gwalsh311** [digitalcredentials/learner-credential-wallet#500]
Would recommend editing instruction text to "Allows sending one or more credentials as a JSON file"

**Comment by alexfigtree** [comment]
This new text is now showing when sharing one or multiple credentials. Can be marked as closed.

**Comment by alexfigtree** [comment]
Keeping open until after deployment

**Comment by alexfigtree** [comment]
Deployed to both Google Play and App Store (release 2.1.0-build80), closing ticket.
