### ISSUE TITLE
react-native-camera is deprecated (used w/ QR Scanner)

### ISSUE THREAD

**Issue by jennacioffi** [digitalcredentials/learner-credential-wallet#503]
We use react-native-camera for our QR scanner currently. According to [their repo](https://github.com/react-native-camera/react-native-camera), we should be using [react-native-vision-camera](https://github.com/mrousavy/react-native-vision-camera) instead now.

**Comment by alexfigtree** [comment]
Are now using `react-native-vision-camera`. Implemented, will be deployed with first post-RN upgrade release.

**Comment by alexfigtree** [comment]
Released version 2.1.0-build80 to prod, closing this ticket
