### ISSUE TITLE
Register a Universal app link for LCW with iOS and Android

### ISSUE THREAD

**Issue by dmitrizagidulin** [digitalcredentials/learner-credential-wallet#505]
LCW currently works with deep links using a custom protocol handler. However, to make it work with the new CHAPI Wallet Selector (see issue https://github.com/digitalcredentials/learner-credential-wallet/issues/504), we need to enable universal app link for iOS and Android.

## For iOS
* [x] Associate the `https://lcw.app` domain with the LCW ios app. See https://developer.apple.com/documentation/xcode/supporting-associated-domains for instructions. (PR https://github.com/digitalcredentials/learner-credential-wallet-site/pull/12)
* [x] Add the associated domain entitlement to LCW. See https://developer.apple.com/documentation/xcode/supporting-associated-domains#Add-the-associated-domains-entitlement-to-your-app. (PR https://github.com/digitalcredentials/learner-credential-wallet/pull/520)

## For Android
* [x] Associate `https://lcw.app` with LCW Android app, and add corresponding entitlement. See https://developer.android.com/studio/write/app-link-indexing

**Comment by dmitrizagidulin** [comment]
Completed.

**Comment by kayaelle** [comment]
Thanks!
