### ISSUE TITLE
Achievement Type appears in two locations on a credential display

### ISSUE THREAD

**Issue by bmuramatsu** [digitalcredentials/learner-credential-wallet#506]
Achievement Type is appearing in two locations in LCW v2.0.13 in iOS and Android, one under the Credential Name and once in the body of the credential.

1. Achievement Type should probably only appear in one location.
2. If we leave Achievement Type under the Credential Name, we should consider if label is necessary for end-user (not standards wonk) understanding.
3. If we retain Achievement Type in the body of the credential, I think it's less important than the Subject Name from an end user perspective. I would order it below Subject Name.

<img src="https://github.com/digitalcredentials/learner-credential-wallet/assets/752326/67fec2e0-14ec-4c8d-b6ba-ac6ad8d4ff6d" width="30%">

**Comment by alexfigtree** [comment]
@dmitrizagidulin and I discussed and decided that it would make sense to remove the text from where it takes up more space (i.e., below Issuance Date), which would allow the user to see more content on this screen.
