### ISSUE TITLE
Prioritizing display of VC Fields When No RenderMethod Provided

### ISSUE THREAD

**Issue by kayaelle** [digitalcredentials/learner-credential-wallet#509]
From discussion at #460 

> @kayaelle One thing that has confused me for a while now is the presence of `name`, `description`, and `image` at multiple levels of the credential. In the event that `name`, `description`, or `image` appear both at the root level of the credential _and_ at `credentialSubject.achievement`, how should the wallet handle that?

I think this is confusing too. The name, description, and image are intended to be specific to the VC that was issued whereas the `credentialSubject.achievement` is intended to be the generic description that applies to anyone that the badge was issued to. Up for discussion could be prioritizing the root level over the credentialSubject.achievement content.

I think this is a related but different discussion about prioritizing fields in VCs versus OB3. I'll make an issue for discussion. Note that currently this wallet is only displaying Open Badges fields.

**Comment by alexfigtree** [comment]
Closing in favor of: https://github.com/digitalcredentials/learner-credential-wallet/issues/513
