### ISSUE TITLE
Title adjustment on BGV credential 

### ISSUE THREAD

**Issue by gwalsh311** [digitalcredentials/learner-credential-wallet#531]
Title in credential bleeds over on mobile page
![LCW - BGV issue](https://github.com/digitalcredentials/learner-credential-wallet/assets/44575606/c29f67e0-d8cd-4987-b8b3-5970b549a0cc)

**Comment by kayaelle** [comment]
@alexfigtree - I think we should up the priority on this.Below are sceenshots of another credential where the title goes offscreen.
![LCW-screen2](https://github.com/digitalcredentials/learner-credential-wallet/assets/206059/d64649de-0f8a-439b-8964-677583a06b40)
![lcw-screen1](https://github.com/digitalcredentials/learner-credential-wallet/assets/206059/644c7290-fc5d-41f9-816d-84326d819cb7)

**Comment by alexfigtree** [comment]
Ok, changing priority to Priority and moving to To Do.

**Comment by alexfigtree** [comment]
Keeping open until after deployment

**Comment by alexfigtree** [comment]
Deployed to both Google Play and App Store (release 2.1.0-build80), closing ticket.

**Comment by alexfigtree** [comment]
Confirming that this still works on Build 82

**Comment by alexfigtree** [comment]
Completed, moving to Done.
