### ISSUE TITLE
Extract Verifier+ location to config

### ISSUE THREAD

**Issue by dmitrizagidulin** [digitalcredentials/learner-credential-wallet#542]

**Comment by kayaelle** [comment]
@dmitrizagidulin - can you provide more details for this issue. Is it in progress or should it be in backlog?

**Comment by dmitrizagidulin** [comment]
Merged into main as of PR #538, tested on android & ios.

**Comment by dmitrizagidulin** [comment]
Released to stores as `v2.0.19-build74`
