### ISSUE TITLE
Error: crypto.subtle not found

### ISSUE THREAD

**Issue by kezike** [digitalcredentials/learner-credential-wallet#554]
When try to verify credentials, we encounter this error:

`Error: crypto.subtle not found`

Reproduction:
- Clone LCW repo
- Run `npm install`
  - Android: Run `npm run android` or use Android Studio to launch app
  - iOS: Run `npm run ios` or use XCode to launch app
- Visit https://lcw.app/register-wallet and follow instructions to register LCW with your browser
- Visit https://vcplayground.org/issuer
- Press gear icon, select `VC-API to any Wallet`, and press `Done`
- Select badge titled `Open Badge`
- Press `ISSUE VERIFIABLE CREDENTIAL`
- Press `SIGN IN WITH YOUR DID`
- Press `Next` in the modal titled `Store Credentials`
- Select the LCW app
- In the app, you will see a modal titled `Exchange Credentials Request`. Press `Yes` to continue.
- The screen will stall on a modal titled `Retrieving Credential`
- In the Metro terminal, you will see `Error: crypto.subtle not found`

Note: This is only one of a few ways to reproduce this error.

**Comment by vonovak** [comment]
Hello, can you please confirm that you're seeing this is on the master branch? Thank you 👍

**Comment by dmitrizagidulin** [comment]
This is fixed in the RN branch / PR #550

**Comment by alexfigtree** [comment]
Re-opening until after deployment of RN upgrade

**Comment by alexfigtree** [comment]
Testing needed on Build 81

**Comment by alexfigtree** [comment]
No longer occurring in Build 82, closing.

**Comment by alexfigtree** [comment]
Completed, moving to Done.
