### ISSUE TITLE
Q&A- Tec: LCW Web wallet

### ISSUE THREAD

**Issue by MyriamLara** [digitalcredentials/learner-credential-wallet#565]
When making a credential claim from a Mobile or Web device, we are redirected to the Web Wallet. Is this behavior of redirection to a web wallet correct? Since we expected that it would redirect us to the LCW on Mobile.
We share evidence with you, in image 6, is where we were redirected when opening the invitation link, instead of going to LCW, it sent us - apparently - a Web Wallet.

Image 6
![image](https://github.com/digitalcredentials/learner-credential-wallet/assets/95261927/3ec51691-ed71-431f-a5a5-e57e37f84c0c)

In relation to the issue of claiming the credential, it generates a warning or error when reading the QR code from the LCW. Do you think this error is because we are not yet registered as issuers in the DCC registry? We show you evidence in image 7.
![image](https://github.com/digitalcredentials/learner-credential-wallet/assets/95261927/b33b1eb8-ad86-41a6-a69e-a252283d39be)

**Comment by alexfigtree** [comment]
@MyriamLara Are you using the Learning Foundation version of the Admin Dashboard or ours? Also, what version?

**Comment by alexfigtree** [comment]
Hola @AngelOCrz94 @MyriamLara nos puede mandar el codigo QR que estas tratando de escañar, or por lo menos, el JSON que corresponde?

**Comment by AngelOCrz94** [comment]
Esto es el código QR

![image](https://github.com/digitalcredentials/learner-credential-wallet/assets/116585767/937e6b61-105b-4bcb-9a67-646b3c69c9f8)

Este es la data del json

{
  "type": [
    "VerifiableCredential",
    "OpenBadgeCredential"
  ],
  "name": "Successful Installation",
  "issuer": {
    "url": "https://digitalcredentials.mit.edu",
    "type": "Profile",
    "name": "DCC Test Issuer",
    "image": {
      "id": "https://certificates.cs50.io/static/success.jpg",
      "type": "Image"
    },
    "description": "A test DID used to issue test credentials",
    "id": "did:key:z6MktdZHB8NkAnjeWy6jcFyvYvm4tPoJS1c6wu1CEMsq9HLY"
  },
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://purl.imsglobal.org/spec/ob/v3p0/context-3.0.2.json",
    "https://w3id.org/vc/status-list/2021/v1",
    "https://w3id.org/security/suites/ed25519-2020/v1"
  ],
  "expirationDate": "2025-01-01T00:00:00Z",
  "credentialSubject": {
    "type": "AchievementSubject",
    "name": "Me!",
    "achievement": {
      "id": "http://digitalcredentials.mit.edu",
      "type": "Achievement",
      "name": "Successful Installation",
      "image": {
        "id": "https://certificates.cs50.io/static/success.jpg",
        "type": "Image"
      },
      "criteria": {
        "narrative": "Successfully installed the DCC issuer."
      },
      "description": "DCC congratulates you on your successful installation of the DCC Issuer."
    },
    "id": "did:key:z6MkrV8A6NDsBuAfZo6NXxPLCfeJ5hSCGuLthLYZgytTmJrB"
  },
  "id": "65f21ebccc953a94cc0c27c1",
  "credentialStatus": {
    "id": "https://ti-tecnologico-de-monterrey-oficial.github.io/myproject-status-list/SFXSIVP1D8#25",
    "type": "StatusList2021Entry",
    "statusPurpose": "revocation",
    "statusListIndex": "25",
    "statusListCredential": "https://ti-tecnologico-de-monterrey-oficial.github.io/myproject-status-list/SFXSIVP1D8"
  },
  "issuanceDate": "2024-03-14T22:32:52Z",
  "proof": {
    "type": "Ed25519Signature2020",
    "created": "2024-03-14T22:32:52Z",
    "verificationMethod": "did:key:z6MktdZHB8NkAnjeWy6jcFyvYvm4tPoJS1c6wu1CEMsq9HLY#z6MktdZHB8NkAnjeWy6jcFyvYvm4tPoJS1c6wu1CEMsq9HLY",
    "proofPurpose": "assertionMethod",
    "proofValue": "z2TjKSkcLnHFuVuhg89u6CEMiYrS5Dwu9HvMuomiAVVohMxzDzfhWRJmeQ1Q6fE6bREWNtE4LtaKx3HBTQXUJFJiz"
  }
}

**Comment by alexfigtree** [comment]
@AngelOCrz94 Aparece que este codigo QR se esta generando por medio de la 'learning economy' version del Admin Dashboard. Tendrias que generarlo usando nuestra version del Admin Dashboard para que te funciones.

**Comment by alexfigtree** [comment]
@AngelOCrz94 Hola Angel, nos puede confirmar si este asunto todavia te esta afectando?

**Comment by AngelOCrz94** [comment]
Ya no sigue afectando. Puedes cerrarlo

Obtener Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by alexfigtree** [comment]
Confirmed that issue is no longer occurring, closing ticket
