### ISSUE TITLE
PDF display/preview

### ISSUE THREAD

**Issue by jchartrand** [digitalcredentials/learner-credential-wallet#567]
Add an option to display - within the LCW - the PDF rendering of a credential.

This could be something like a button on the main credential page called 'Show PDF' that when clicked opens a dialog or page in which the PDF version of the credential is displayed. 

The PDF would be generated on-the-fly, using the same code that is now used to generate the PDF for sharing.

This new display could also be used as a preview when someone wants to share the PDF version of a credential - so that they know exactly what it is that they are sharing.

The PDF version would only be available for credentials with a renderMethod.  Unless we wanted to provide a default PDF rendering - maybe something very similar to what is now shown in the wallet for a credential (logo, title, holder, date, etc.)

**Comment by alexfigtree** [comment]
Kerri: we can wait until after Tec deployment to address

**Comment by alexfigtree** [comment]
Already addressed, closing
