### ISSUE TITLE
Unrecognized platform name visionOS RNKeyChainManager error

### ISSUE THREAD

**Issue by dmitrizagidulin** [digitalcredentials/learner-credential-wallet#598]
Running latest `main` on iOS, build error in XCode:

```
node_modules/react-native-keychain/RNKeychainManager/RNKeychainManager.m:336:20 Unrecognized platform name visionOS
node_modules/react-native-keychain/RNKeychainManager/RNKeychainManager.m:337:35 Use of undeclared identifier 'LABiometryTypeOpticID'
```

**To Reproduce**
1. `git checkout main && git pull`
2. `rm -rf node_modules`
3. `npm i --legacy-peer-deps`
4. `npm run prebuild:ios`
5. Open XCode, Product > Clean Build Folder
6. Select device (in my case, iPhone 8 hardware device), press Play (build) button
7. Get build error.

(Also, if you run into an error on the `prebuild:ios` step, you may have an old version of `cocoapods`, see https://github.com/digitalcredentials/learner-credential-wallet/wiki/Troubleshooting#error-running-npm-run-prebuildios )

**See also:** Upstream issue https://github.com/oblador/react-native-keychain/issues/624

**Comment by alexfigtree** [comment]
Closing.
