### ISSUE TITLE
Register Wallet button not working on Android on Build 58+.

### ISSUE THREAD

**Issue by dmitrizagidulin** [digitalcredentials/learner-credential-wallet#607]
On the current store release (build 58), when initializing a new wallet, the 'Register Wallet' button does not open the `https://lcw.app/register-wallet.html` browser page like it's supposed to - on Android. (it's working on iOS).

**To Reproduce**
Initialize a new wallet and click 'Register Wallet'. Alternatively, if you don't want to reset your wallet, go to Settings > Register Wallet (it should do the same thing).

**Expected behavior**
Mobile browser should open to the register wallet page.
(Instead, no page is opened.)

**Smartphone (please complete the following information):**
 - Device: Android

**Comment by dmitrizagidulin** [comment]
Update: So, I think we're actually running into a React Native bug, https://github.com/facebook/react-native/issues/32311

It's non-blocking though, we can route around it.

**Comment by alexfigtree** [comment]
Published to Google Store, pending merging of PR to main branch

**Comment by alexfigtree** [comment]
This issue is still happening on the latest release of Android, moving back to To Do.

**Comment by alexfigtree** [comment]
Confirmed on fresh install, button still not working, moving ticket to backlog.

**Comment by alexfigtree** [comment]
Tested on 2.1.1 (Build 81) - button now working. Currently in test mode, but ready for prod.

**Comment by alexfigtree** [comment]
Still working on Build 82

**Comment by alexfigtree** [comment]
Completed, moving to Done.
