### ISSUE TITLE
Issues installing on Windows

### ISSUE THREAD

**Issue by alexfigtree** [digitalcredentials/learner-credential-wallet#629]
**Describe the bug**
Issues installing on Windows:

**To Reproduce**

`
npm i --legacy-peer-deps
npm WARN cleanup Failed to remove some directories [
npm WARN cleanup   [
npm WARN cleanup     'C:\\iq4\\dcc3\\learner-credential-wallet\\node_modules\\react-native',
npm WARN cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\iq4\dcc3\learner-credential-wallet\node_modules\react-native\ReactCommon\react\renderer\components\textinput\androidtextinput\react\renderer\components'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\iq4\\dcc3\\learner-credential-wallet\\node_modules\\react-native\\ReactCommon\\react\\renderer\\components\\textinput\\androidtextinput\\react\\renderer\\components'
npm WARN cleanup     }
npm WARN cleanup   ]
npm WARN cleanup ]
npm ERR! code 1
npm ERR! git dep preparation failed
npm ERR! command C:\Program Files\nodejs\node.exe C:\Users\timgu\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js install --force --cache=C:\Users\timgu\AppData\Local\npm-cache --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-run
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm WARN deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm ERR! npm WARN deprecated @humanwhocodes/config-array@0.11.14: Use @eslint/config-array instead
npm ERR! npm WARN deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm ERR! npm WARN deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm ERR! npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm ERR! npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm ERR! npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm ERR! npm WARN deprecated glob@8.1.0: Glob versions prior to v9 are no longer supported
npm ERR! npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm ERR! npm WARN deprecated @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead
npm ERR! npm WARN deprecated @unimodules/core@7.1.2: replaced by the 'expo' package, learn more: https://blog.expo.dev/whats-new-in-expo-modules-infrastructure-7a7cdda81ebc
npm ERR! npm WARN deprecated @unimodules/react-native-adapter@6.3.9: replaced by the 'expo' package, learn more: https://blog.expo.dev/whats-new-in-expo-modules-infrastructure-7a7cdda81ebc
npm ERR! npm WARN cleanup Failed to remove some directories [
npm ERR! npm WARN cleanup   [
npm ERR! npm WARN cleanup     'C:\\Users\\timgu\\AppData\\Local\\npm-cache\\_cacache\\tmp\\git-clone6vHsOU\\node_modules\\@digitalcredentials\\did-method-key',
npm ERR! npm WARN cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\timgu\AppData\Local\npm-cache\_cacache\tmp\git-clone6vHsOU\node_modules\@digitalcredentials\did-method-key\node_modules'] {
npm ERR! npm WARN cleanup       errno: -4048,
npm ERR! npm WARN cleanup       code: 'EPERM',
npm ERR! npm WARN cleanup       syscall: 'rmdir',
npm ERR! npm WARN cleanup       path: 'C:\\Users\\timgu\\AppData\\Local\\npm-cache\\_cacache\\tmp\\git-clone6vHsOU\\node_modules\\@digitalcredentials\\did-method-key\\node_modules'
npm ERR! npm WARN cleanup     }
npm ERR! npm WARN cleanup   ],
npm ERR! npm WARN cleanup   [
npm ERR! npm WARN cleanup     'C:\\Users\\timgu\\AppData\\Local\\npm-cache\\_cacache\\tmp\\git-clone6vHsOU\\node_modules\\@digitalcredentials\\ed25519-signature-2020',
npm ERR! npm WARN cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\timgu\AppData\Local\npm-cache\_cacache\tmp\git-clone6vHsOU\node_modules\@digitalcredentials\ed25519-signature-2020\node_modules'] {
npm ERR! npm WARN cleanup       errno: -4048,
npm ERR! npm WARN cleanup       code: 'EPERM',
npm ERR! npm WARN cleanup       syscall: 'rmdir',
npm ERR! npm WARN cleanup       path: 'C:\\Users\\timgu\\AppData\\Local\\npm-cache\\_cacache\\tmp\\git-clone6vHsOU\\node_modules\\@digitalcredentials\\ed25519-signature-2020\\node_modules'
npm ERR! npm WARN cleanup     }
npm ERR! npm WARN cleanup   ],
npm ERR! npm WARN cleanup   [
npm ERR! npm WARN cleanup     'C:\\Users\\timgu\\AppData\\Local\\npm-cache\\_cacache\\tmp\\git-clone6vHsOU\\node_modules',
npm ERR! npm WARN cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\timgu\AppData\Local\npm-cache\_cacache\tmp\git-clone6vHsOU\node_modules\expo-random\android\src\main'] {
npm ERR! npm WARN cleanup       errno: -4048,
npm ERR! npm WARN cleanup       code: 'EPERM',
npm ERR! npm WARN cleanup       syscall: 'rmdir',
npm ERR! npm WARN cleanup       path: 'C:\\Users\\timgu\\AppData\\Local\\npm-cache\\_cacache\\tmp\\git-clone6vHsOU\\node_modules\\expo-random\\android\\src\\main'
npm ERR! npm WARN cleanup     }
npm ERR! npm WARN cleanup   ]
npm ERR! npm WARN cleanup ]
npm ERR! npm ERR! code 1
npm ERR! npm ERR! git dep preparation failed
npm ERR! npm ERR! command C:\Program Files\nodejs\node.exe C:\Users\timgu\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js install --force --cache=C:\Users\timgu\AppData\Local\npm-cache --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-run
npm ERR! npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm ERR! npm WARN deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm ERR! npm ERR! npm WARN deprecated @humanwhocodes/config-array@0.11.14: Use @eslint/config-array instead
npm ERR! npm ERR! npm WARN deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm ERR! npm ERR! npm WARN deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm ERR! npm ERR! npm WARN deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm ERR! npm ERR! npm WARN deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm ERR! npm ERR! npm WARN deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm ERR! npm ERR! npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm ERR! npm ERR! npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm ERR! npm ERR! npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm ERR! npm ERR! npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm ERR! npm ERR! npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm ERR! npm ERR! npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm ERR! npm ERR! npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm ERR! npm ERR! npm WARN deprecated glob@8.1.0: Glob versions prior to v9 are no longer supported
npm ERR! npm ERR! npm WARN deprecated @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead
npm ERR! npm ERR! npm WARN deprecated @unimodules/core@7.1.2: replaced by the 'expo' package, learn more: https://blog.expo.dev/whats-new-in-expo-modules-infrastructure-7a7cdda81ebc
npm ERR! npm ERR! npm WARN deprecated @unimodules/react-native-adapter@6.3.9: replaced by the 'expo' package, learn more: https://blog.expo.dev/whats-new-in-expo-modules-infrastructure-7a7cdda81ebc
npm ERR! npm ERR! npm WARN cleanup Failed to remove some directories [
npm ERR! npm ERR! npm WARN cleanup   [
npm ERR! npm ERR! npm WARN cleanup     'C:\\Users\\timgu\\AppData\\Local\\npm-cache\\_cacache\\tmp\\git-clonei4bYFU\\node_modules\\isomorphic-webcrypto',
npm ERR! npm ERR! npm WARN cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\timgu\AppData\Local\npm-cache\_cacache\tmp\git-clonei4bYFU\node_modules\isomorphic-webcrypto\node_modules\react-native-securerandom\android\build\intermediates\res\merged\androidTest\debug'] {
npm ERR! npm ERR! npm WARN cleanup       errno: -4048,
npm ERR! npm ERR! npm WARN cleanup       code: 'EPERM',
npm ERR! npm ERR! npm WARN cleanup       syscall: 'rmdir',
npm ERR! npm ERR! npm WARN cleanup       path: 'C:\\Users\\timgu\\AppData\\Local\\npm-cache\\_cacache\\tmp\\git-clonei4bYFU\\node_modules\\isomorphic-webcrypto\\node_modules\\react-native-securerandom\\android\\build\\intermediates\\res\\merged\\androidTest\\debug'
npm ERR! npm ERR! npm WARN cleanup     }
npm ERR! npm ERR! npm WARN cleanup   ]
npm ERR! npm ERR! npm WARN cleanup ]
npm ERR! npm ERR! npm ERR! code 1
npm ERR! npm ERR! npm ERR! git dep preparation failed
npm ERR! npm ERR! npm ERR! command C:\Program Files\nodejs\node.exe C:\Users\timgu\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js install --force --cache=C:\Users\timgu\AppData\Local\npm-cache --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-run
npm ERR! npm ERR! npm ERR! > @digitalcredentials/security-document-loader@5.0.0 prepare
npm ERR! npm ERR! npm ERR! > npm run build
npm ERR! npm ERR! npm ERR!
npm ERR! npm ERR! npm ERR!
npm ERR! npm ERR! npm ERR! > @digitalcredentials/security-document-loader@5.0.0 build
npm ERR! npm ERR! npm ERR! > npm run clear && tsc -p tsconfig.json && ./build-dist.sh
npm ERR! npm ERR! npm ERR!
npm ERR! npm ERR! npm ERR!
npm ERR! npm ERR! npm ERR! > @digitalcredentials/security-document-loader@5.0.0 clear
npm ERR! npm ERR! npm ERR! > rimraf dist/*
npm ERR! npm ERR! npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm ERR! npm ERR! npm WARN deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm ERR! npm ERR! npm ERR! npm WARN deprecated @humanwhocodes/config-array@0.11.14: Use @eslint/config-array instead
npm ERR! npm ERR! npm ERR! npm WARN deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm ERR! npm ERR! npm ERR! npm WARN deprecated eslint-config-standard-with-typescript@23.0.0: Please use eslint-config-love, instead.
npm ERR! npm ERR! npm ERR! npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm ERR! npm ERR! npm ERR! npm WARN deprecated glob@8.1.0: Glob versions prior to v9 are no longer supported
npm ERR! npm ERR! npm ERR! npm WARN deprecated @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead
npm ERR! npm ERR! npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm ERR! npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm ERR! npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm ERR! npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm ERR! npm ERR! '.' is not recognized as an internal or external command,
npm ERR! npm ERR! npm ERR! operable program or batch file.
npm ERR! npm ERR! npm ERR! npm ERR! code 1
npm ERR! npm ERR! npm ERR! npm ERR! path C:\Users\timgu\AppData\Local\npm-cache\_cacache\tmp\git-clonepfZeVA
npm ERR! npm ERR! npm ERR! npm ERR! command failed
npm ERR! npm ERR! npm ERR! npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c npm run build
npm ERR! npm ERR! npm ERR!
npm ERR! npm ERR! npm ERR! npm ERR! A complete log of this run can be found in: C:\Users\timgu\AppData\Local\npm-cache\_logs\2024-07-08T21_35_06_386Z-debug-0.log
npm ERR! npm ERR!
npm ERR! npm ERR! npm ERR! A complete log of this run can be found in: C:\Users\timgu\AppData\Local\npm-cache\_logs\2024-07-08T21_34_30_269Z-debug-0.log
npm ERR!
npm ERR! npm ERR! A complete log of this run can be found in: C:\Users\timgu\AppData\Local\npm-cache\_logs\2024-07-08T21_34_14_773Z-debug-0.log

npm ERR! A complete log of this run can be found in: C:\Users\timgu\AppData\Local\npm-cache\_logs\2024-07-08T21_34_03_684Z-debug-0.log
`

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by dmitrizagidulin** [comment]
This may need to be "Won't Fix" -- this project is not really meant to be developed on Windows. Nor on Linux, sadly, since only MacOS allows for iOS development.

**Comment by kayaelle** [comment]
Agree w/ @dmitrizagidulin

**Comment by alexfigtree** [comment]
Agree to close this issue because mobile dev not possible on Windows
