### ISSUE TITLE
"Issued To" Not Displaying When Using Identifier in CredentialSubject

### ISSUE THREAD

**Issue by kayaelle** [digitalcredentials/learner-credential-wallet#632]
**Describe the bug**
In relation to closed issue:
`https://github.com/digitalcredentials/learner-credential-wallet/issues/539`

This credential template: https://dashboard.dcconsortium.org/admin/collections/credential-template/66a3b2db6789dd1f426dab93 should produce a credential than uses the code implemented for issue #539 but "Issued To" is not displaying in the LCW. 

It is displaying fine in the signed example that @alexfigtree mentions in #539 but this is because the credential also contains credentialSubject.name - the old way that we have included Issued to. 

**To Reproduce**
1. Use the demo issuer to issue a credential to the LCW using this template: https://dashboard.dcconsortium.org/admin/collections/credential-template/66a3b2db6789dd1f426dab93
2. View Credential 

Alternative way to reproduce:
 re-sign example that @alexfigtree mentions in #539 without credentialSubject.name in the data.

**Expected behavior**
Issued To should be displayed in the credential display if there is an identifier in the credential subject that looks like:

`"identifier":[
{
"type":"IdentityObject",
"hashed":false,
"identityHash":"Sam Smith",
"identityType":"name"}
],`

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by alexfigtree** [comment]
Related to https://github.com/digitalcredentials/learner-credential-wallet/issues/539

**Comment by alexfigtree** [comment]
Need to re-release on iOS Test Flight to verify issue; waiting from MIT re: profile/cert issue in order to Distribute app

**Comment by alexfigtree** [comment]
Display rules for Open Badges:

When both credentialSubject.name and identityHash (create new issue)
- Open Badges: prioritize identityObject ignore credentialSubject.name //ideally

When identityHash only (do not show up for VC's)
- identityHash shows

When both are missing:
- Do not show "Issued To"

**Comment by alexfigtree** [comment]
Currently passing Rules 2 and 3 above, opened new ticket for 1 (New display rule for open badges #641) on Build 82, moving to Release Ready

**Comment by alexfigtree** [comment]
Completed, moving to Done.
