### ISSUE TITLE
Update Target API Level

### ISSUE THREAD

**Issue by alexfigtree** [digitalcredentials/learner-credential-wallet#633]
Update Target API Level needed on Android

<img width="1132" alt="Screenshot 2024-08-28 at 10 49 25 AM" src="https://github.com/user-attachments/assets/9e51fb9b-08e4-403c-8e59-cc278bbaa826">

**Comment by alexfigtree** [comment]
Being worked on as a part of https://github.com/digitalcredentials/ops/issues/15

**Comment by dmitrizagidulin** [comment]
Addressed by PR #635

**Comment by alexfigtree** [comment]
Will need to incorporate #635 into Build 82, forthcoming.
