### ISSUE TITLE
ViewPropTypes error on Android

### ISSUE THREAD

**Issue by mariopel** [digitalcredentials/learner-credential-wallet#646]
**Describe the bug**
ERROR  ViewPropTypes will be removed from React Native, along with all other PropTypes. We recommend that you migrate away from PropTypes and switch to a type system like TypeScript. If you need to continue using ViewPropTypes, migrate to the 'deprecated-react-native-prop-types' package.
**To Reproduce**
JDK 17 
Node.js 20.18
npm 10.8.2
nvm 0.39.1
Android Studio Koala

npm install  - - legacy-peer-deps
npm run prebuild:android

npm start
npm run android

**Expected behavior**
No errors

**Screenshots**
![image](https://github.com/user-attachments/assets/441dddb4-cc66-4c0b-9a01-89e4ecbf3f0e)

**Desktop (please complete the following information):**
 - OS: Linux - Distribution Ubuntu 22.04 Desktop

 - Browser [chrome]
 - Version [129.0.06668.100 64 bit]

**Smartphone (please complete the following information):**
 - Device: [POCO M3 Pro 5G]
 - OS: [Android 13 TP1A]
 - Browser [chrome]
 - Version [129.0.6668]

**Additional context**
Hardware PC:
 CPU: Ryzen3 2200G, RAM:12 GByte, Storage: M.2 NVME 480 GByte

Android Studio Koala
   Android 14 (UpsideDownCake) SDK
   Android SDK Platform 34
  Google APIs Intel x86 Atom System Image
  Android SDK Build-Tools 34.0.0
  AVD: Pixel 5  Android UpsideDownCake API Level 34
  Watchman (installed with homebrew)

**Comment by alexfigtree** [comment]
@mariopel Please see and follow: https://github.com/digitalcredentials/learner-credential-wallet/issues/575. We are planning for a fix for this issue starting in November. Closing this as a duplicate.
