### ISSUE TITLE
App crashes after viewing credential

### ISSUE THREAD

**Issue by mlisle** [digitalcredentials/learner-credential-wallet#69]
I tried adding credentials listed at https://github.com/digitalcredentials/docs/issues/10 and encountered the following:

1. Add credential using QR code
2. Upon success, click "Added to Wallet"
3. Arrive at Credential Preview, Click Home
4. See credential from step 1. Tap that credential.
5. App crashes
6. Upon reopening app, my wallet is empty again.

My wallet remains empty until after I add another credential, at which point I can temporarily see credential from step 1. But once I try to select a credential, the app crashes and my wallet empties again.

**Comment by bmuramatsu** [comment]
Ok I can reproduce this bug. Reset the wallet. Add a couple credentials from the Setting menu using the dev credential option. Preview any of the credentials. Close the app--but do not logout. Reopen the app, try and view a credential, it crashes. Reopen app, see no credentials. Add more credential(s). View the home screen (list of credentials). All the previous credentials are there.

@mlisle  Can you try the add, close app, reopen app, preview credential.

**Comment by mlisle** [comment]
@bmuramatsu I can try that. But I just discovered a slightly different way to reproduce this (or should it be a different issue)?...

- Open Wallet, home screen is empty (no credentials)
- Switch to Settings
- Tap App credential (dev)
- Switch back to home screen... credentials are there again

I can kill the app (double tap home button) and reopen the app... and it happens every time.

**Comment by bmuramatsu** [comment]
that sounds like the same issue to me...
