### ISSUE TITLE
About Screen Updates

### ISSUE THREAD

**Issue by bmuramatsu** [digitalcredentials/learner-credential-wallet#70]
Multiple updates to the About Screen

- Add Accessibility link to https://accessibility.mit.edu
- Add Acknowledgements Section--discuss if link to Github https://github.com/digitalcredentials/learner-credential-wallet#acknowledgements or self contained in apps
~~- Consider license file with included libraries~~
- Add link to Privacy and Terms of Service (once we create them!)
- License?

**Comment by sethduffin** [comment]
@bmuramatsu, my apologies, I must've missed this. I've added a PT story so this can get into iteration planning

https://www.pivotaltracker.com/story/show/180525340

**Comment by bmuramatsu** [comment]
No you didn't miss it! We hadn't figured out what to do about Acknowledgements yet.

**Comment by bmuramatsu** [comment]
We decided to change the "For more information" link from DCC website to http://eduwallet.app.

Closing this.
