### ISSUE TITLE
Deleted credential cannot be readded to wallet

### ISSUE THREAD

**Issue by bmuramatsu** [digitalcredentials/learner-credential-wallet#80]
From reset wallet. Finish setup.

Add credential from https://github.com/digitalcredentials/docs/issues/10 multiple credentials with invalid signature:
![135905712-2e9baf4d-3489-40eb-966f-6e3da5cc2a3c](https://user-images.githubusercontent.com/752326/144519928-0d7ebf1d-d041-4193-b155-e79d80750d93.png)

Delete second credential. Only 1 credential remains in the wallet.
<img src="https://user-images.githubusercontent.com/752326/144520141-65ba7682-c053-46fe-afd4-a070c68f55e6.png" width=50%>

Try to readd credentials using the same two from QR code.

Both credentials appear as "Aready in Wallet"
<img src="https://user-images.githubusercontent.com/752326/144520159-8e10c3c2-a8d0-4062-95c6-8214d6e0c4bc.png" width=50%>

But, only 1 credential in the wallet...
<img src="https://user-images.githubusercontent.com/752326/144520141-65ba7682-c053-46fe-afd4-a070c68f55e6.png" width=50%>

**Comment by sethduffin** [comment]
Thanks for the repro documentation. I've added a story in PT and will take a look at it.
https://www.pivotaltracker.com/story/show/180524965

**Comment by bmuramatsu** [comment]
Appears to be resolved, I forget which PR, closing this.

**Comment by sethduffin** [comment]
I believe this is still an issue.
We're using the `id` field to differentiate credentials but not all contain an `id` so it treats them as duplicates. 
We discussed using the `proofValue` to identify credentials going forward.
