### ISSUE TITLE
Version number display on About screen

### ISSUE THREAD

**Issue by bmuramatsu** [digitalcredentials/learner-credential-wallet#82]
Is there an automated way of displaying the current build number in iOS and Android at the bottom of the About screen and maybe the Home screen so we can visually determine the version number after building it?

I think we're going to want to display this somewhere.

(Seth, I'm ok with adding this as a new feature and spending time to implement it and including getting Brandon Findlay involved in suggesting a location for it.)

**Comment by sethduffin** [comment]
@bmuramatsu I believe there is support for that with this library: https://github.com/react-native-device-info/react-native-device-info

I'll add a story and contact Brandon Findlay about the location.

**Comment by bmuramatsu** [comment]
Including build #.

**Comment by bmuramatsu** [comment]
Closed with https://github.com/digitalcredentials/learner-credential-wallet/pull/126
