### ISSUE TITLE
Android build fails when using nodejs installed with asdf on linux

### ISSUE THREAD

**Issue by stuartf** [digitalcredentials/learner-credential-wallet#83]
I encountered this bug when trying to build with node using asdf https://github.com/expo/expo/issues/8547

**Comment by bmuramatsu** [comment]
Another expo holdover bug @sethduffin?

**Comment by sethduffin** [comment]
@bmuramatsu it looks like it. I'll dive into it a bit more to see what we'd need to fix.

**Comment by sethduffin** [comment]
Hi @stuartf, we've applied the patch suggested in the expo issue you've linked to. Could check out the branch in PR #90 and confirm that the issue has been resolved?

**Comment by stuartf** [comment]
@sethduffin it needed a little more to make it work, I've submitted #92 which extends #90 and fixes the build for me.

**Comment by sethduffin** [comment]
@stuartf Right on, thanks for submitting that PR!

**Comment by dirkcuys** [comment]
I can confirm that the project builds and run on Linux (Ubuntu 20.04 and Node v16.13.2)

**Comment by dmitrizagidulin** [comment]
Excellent, thanks for your work everyone! Closing this issue.
