### ISSUE TITLE
Update credential verify status text

### ISSUE THREAD

**Issue by dmitrizagidulin** [digitalcredentials/learner-credential-wallet#98]
Credential not verified text:

This could mean that the credential:
* is in an unrecognized format
* the digital signature does not validate ~~(aka has been tampered with)~~
* has not been issued by a registered institution
* the issuing institution could not be reached to verify the credential
* has expired
* has been revoked by the issuing institution

**Comment by sethduffin** [comment]
For the positive version of this (credential verified text), I've used the inverse of these statements. Let me know this works:

> This means that the credential:
> * is in a recognized format
> * the digital signature does validate (aka has not been tampered with)
> * has been issued by a registered institution
> * the issuing institution could be reached to verify the credential
> * has not expired
> * has not been revoked by the issuing institution

**Comment by bmuramatsu** [comment]
One change... to simplify.


This means that the credential:

is in a recognized format
the digital **signature validates** (aka has not been tampered with)
has been issued by a registered institution
the issuing institution could be reached to verify the credential
has not expired
has not been revoked by the issuing institution

**Comment by bmuramatsu** [comment]
Also let's drop the aka parenthetical for simplicity.

**Comment by sethduffin** [comment]
Sounds good, thanks!
